### PR TITLE
Add document this code action to annotation declarations

### LINKED ISSUE #34423: `Document This` code action is not shown for annotation declarations
**Description:**
Write an annotation like:
```ballerina
public const annotation Data MyAnnot on source worker, source var;
```
and move your cursor over it. `Document This` code action is not suggested.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta6

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #34423

## Samples
https://user-images.githubusercontent.com/46120162/166621556-c978cf7c-7f62-4fa0-9c0b-c597ce320d08.mp4

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]
LGTM! Nice usage of optionals and streams!

**Review by IMS94 — CHANGES_REQUESTED** [review]
Shall we improve the diff coverage?

**Comment by gayalkuruppu** [comment]
> Shall we improve the diff coverage?

Done

**Review by IMS94 — APPROVED** [review]

**Review by TharushiJay — APPROVED** [review]
LGTM!

**Pull request merged**
