### PR TITLE
Remove `--debug` option from `build` CLI help

### PR DESCRIPTION
**Pull request by praveennadarajah**
## Purpose
This PR will remove the `--debug` option from `build` CLI help.

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/34169 https://github.com/ballerina-platform/ballerina-lang/issues/33748

### CODE REVIEW

**Review by NipunaRanasinghe — COMMENTED** [review]
@praveennadarajah We need to enable/remove the disabled tests IMO.

**Comment by praveennadarajah** [comment]
> @praveennadarajah We need to enable/remove the disabled tests IMO.

@NipunaRanasinghe I have removed the disabled tests via https://github.com/ballerina-platform/ballerina-lang/pull/34168/commits/ec81ffc373b80c2e7ad6f932a83689a6b072c28d.

**Review by NipunaRanasinghe — COMMENTED** [review]
@praveennadarajah We might need to remove the debug flag related implementation from `io.ballerina.cli.cmd.BuildCommand` as well.

**Comment by praveennadarajah** [comment]
> @praveennadarajah We might need to remove the debug flag related implementation from `io.ballerina.cli.cmd.BuildCommand` as well.

@NipunaRanasinghe Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/34168/commits/ebc921ecf6c0d602b5c71ba8de1f957ed90fa95e

**Review by NipunaRanasinghe — APPROVED** [review]

**Pull request merged**
