### PR TITLE
Fix typos in Objects BBE in master

### PR DESCRIPTION
**Pull request by gimantha**
$Subject

### CODE REVIEW

**Comment by anupama-pathirage** [comment]
@gimantha Can you please rebase this to master branch?

**Comment by pubudu91** [comment]
> @gimantha Can you please rebase this to master branch?

Should send this fix to both `master` and `ballerina-1.1.x` right?

**Comment by gimantha** [comment]
> @gimantha Can you please rebase this to master branch?

sure.. sent to both 1.1.x and master

**Comment by gimantha** [comment]
> > @gimantha Can you please rebase this to master branch?
> 
> Should send this fix to both `master` and `ballerina-1.1.x` right?

sent to both

**Pull request merged**
