### PR TITLE
[Bindgen Tool] Allow passing null values into Ballerina bindings generated on java string objects

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/39059

## Approach
Refer to the table below to see the list of impacted changes, related to Ballerina bindings generation for java `String` objects

| Context   | Existing | New |
| -------- | ----------- | ----------- |
| function parameter types    | string       | string? |
|    | string[]       | string?[] |
| function return types   |  string?       | string? |        
|   | string[]?       | string?[]? |

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [x] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by sameerajayasoma** [comment]
The design level changes looks good to me.

**Comment by sameerajayasoma** [comment]
Should we make the function parameter type to this `string?[]?`

**Comment by NipunaRanasinghe** [comment]
> Should we make the function parameter type to this `string?[]?`

@sameerajayasoma I also had the same concern, but, if we are to support passing `null` values for java array objects we'd have to rethink of all the other array types (including the primitive arrays, i.e. `int[]` -> `int[]?`) as a whole IMO. 

And if thats also a valid requirement probably we can look into that improvement separately. WDYT?

**Comment by sameerajayasoma** [comment]
> > Should we make the function parameter type to this `string?[]?`
> 
> @sameerajayasoma I also had the same concern, but, if we are to support passing `null` values for java array objects we'd have to rethink of all the other array types (including the primitive arrays, i.e. `int[]` -> `int[]?`) as a whole IMO.
> 
> And if that's also a valid requirement probably we can look into that improvement separately. WDYT?

Shall we have a chat about this? I think we need to look at the overall design as you said.

**Comment by NipunaRanasinghe** [comment]
> Shall we have a chat about this? I think we need to look at the overall design as you said.

@sameerajayasoma yeah that'll be better. I'll schedule one in early next week

**Pull request closed without merging**
