### PR TITLE
Improve parser recovery in expression context within the func-def at top-level

### LINKED ISSUE #26317: Semantic API's visibleSymbol API drops function symbols
**Description:**
Consider the following source,

```
public function testFunction() {
    if <cursor>
}

function doSomeTask() {
    // todo: here goes a certain task
}

```

In the given cursor position, `doSomeTask` function should be visible

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #26317 

## Approach
N/A

## Samples
Source:
```bal
public function testFunction() {
    if  //<cursor>
}

function doSomeTask() {
    // here goes a certain task
}
```

Previous Recovery:
```bal
public function testFunction() {
    if  INVALID[}] function INVALID[doSomeTask]() {} MISSING[{] // Recovers as anonymous-function-expr 
    MISSING[}] 
MISSING[}]
```

New Recovery:
```bal
public function testFunction() {
    if  MISSING[] MISSING[{]
    }
MISSING[}]

function doSomeTask() {
    // here goes a certain task
}
```

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by nadeeshaan — DISMISSED** [review]
Changes affected to lang server looks good. Hence approving

**Comment by lochana-chathura** [comment]
@pcnfernando can you verify whether the commit `Update testSymbolLookupInQuery() test` (72e3db0) is okay?

**Review by rdulmina — DISMISSED** [review]
LGTM

**Review by pcnfernando — CHANGES_REQUESTED** [review]
Query test update seems to be incorrect

**Review by pcnfernando — APPROVED** [review]

**Pull request merged**
