### PR TITLE
[Master] Fix `ArrayIndexOutOfBoundsException` for object type recovery in record fields

### LINKED ISSUE #37177: Parser crashes with `ArrayIndexOutOfBoundsException` for object type recovery
**Description:**
$subject. 

Consider the below code.
```bal
type MediationGenPayload record {
    string componentId;
    object data; // should be object{}
}; 

configurable string cicdBaseUrl = ?; 

public isolated function triggerRepoInitAction(RepoInitPayload payload) returns boolean {

}
```

<details>
  <summary><b>stacktrace</b>  (<i>click to expand</i>)</summary>

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at io.ballerina.compiler.internal.parser.tree.STNode.childInBucket(STNode.java:66)
	at io.ballerina.compiler.internal.parser.utils.ConditionalExprResolver.getQualifiedNameRefNode(ConditionalExprResolver.java:60)
	at io.ballerina.compiler.internal.parser.utils.ConditionalExprResolver.getQualifiedNameRefNode(ConditionalExprResolver.java:62)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseConditionalExpression(BallerinaParser.java:13137)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpressionRhsInternal(BallerinaParser.java:5564)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpressionRhs(BallerinaParser.java:5492)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5038)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5032)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:5027)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseExpression(BallerinaParser.java:4958)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFieldDescriptorRhs(BallerinaParser.java:4239)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseIndividualRecordField(BallerinaParser.java:4051)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFieldOrRestDescriptorRhs(BallerinaParser.java:4201)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseRecordField(BallerinaParser.java:4000)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseRecordField(BallerinaParser.java:3992)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFieldOrRestDescriptor(BallerinaParser.java:3981)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseFieldOrRestDescriptor(BallerinaParser.java:3985)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseRecordTypeDescriptor(BallerinaParser.java:3829)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2713)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptorInternal(BallerinaParser.java:2569)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2560)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2551)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTypeDescriptor(BallerinaParser.java:2532)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseModuleTypeDefinition(BallerinaParser.java:3576)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:999)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:984)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:499)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseTopLevelNode(BallerinaParser.java:431)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:335)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:100)
	at io.ballerinalang.compiler.parser.test.TestParser.testParser(TestParser.java:46)
	at io.ballerinalang.compiler.parser.test.TestParser.main(TestParser.java:40)
```
</details>

**Affected Versions:**
2201.1.1

### PR DESCRIPTION
**Pull request by prakanth97**
## Purpose

Fixes #37177

## Approach
If `parentNode` is empty return `null`, otherwise continue the flow.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by rdulmina — APPROVED** [review]

**Comment by rdulmina** [comment]
@gimantha we can send this to `2201.2.x` right? Since this is not a breaking change

**Comment by gimantha** [comment]
> @gimantha we can send this to `2201.2.x` right? Since this is not a breaking change

Yes.. We should send this to 2201.2.x

**Comment by prakanth97** [comment]
> > @gimantha we can send this to `2201.2.x` right? Since this is not a breaking change
> 
> Yes.. We should send this to 2201.2.x

Do we need to send this to 2201.1.x?

**Comment by gimantha** [comment]
> Do we need to send this to 2201.1.x? @gimantha

Since this issue is reproducible in 2201.1.x, i think we should send a PR to 2201.1.x

**Pull request merged**
