### PR TITLE
Fix test failures when building in Windows env

### PR DESCRIPTION
**Pull request by pranavan15**
## Purpose
Fixing the build time test failures in Windows OS.

### CODE REVIEW

**Comment by hasithaa** [comment]
Hi Pranavan, 

Following test are failing in windows.

```
[ERROR] Tests run: 3401, Failures: 12, Errors: 0, Skipped: 0, Time elapsed: 462.735 s <<< FAILURE! - in TestSuite
[ERROR] testDocAnnotation(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.057 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Documentation for Test annotation] but found [Documentation for Test annotation
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocAnnotation(MarkdownDocumentationTest.java:56)

[ERROR] testDocConnectorFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.051 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Test Connector] but found [Test Connector
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocConnectorFunction(MarkdownDocumentationTest.java:280)

[ERROR] testDocConstant(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.02 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Documentation for testConst constant] but found [Documentation for testConst constant
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocConstant(MarkdownDocumentationTest.java:78)

[ERROR] testDocFiniteTypes(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.024 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Documentation for state enum] but found [Documentation for state enum
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocFiniteTypes(MarkdownDocumentationTest.java:97)

[ERROR] testDocFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.043 s  <<< FAILURE!
java.lang.AssertionError:
expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
]SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocFunction(MarkdownDocumentationTest.java:154)

[ERROR] testDocNativeFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError:
expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
]SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocNativeFunction(MarkdownDocumentationTest.java:396)

[ERROR] testDocService(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.365 s  <<< FAILURE!
]ava.lang.AssertionError: expected [PizzaService HTTP Service] but found [PizzaService HTTP Service
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocService(MarkdownDocumentationTest.java:245)

[ERROR] testDocType(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.022 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Documentation for Test type] but found [Documentation for Test type
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocType(MarkdownDocumentationTest.java:132)

[ERROR] testInlineCode(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.AssertionError:
expected [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``] but found [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
] ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testInlineCode(MarkdownDocumentationTest.java:325)

[ERROR] testInlineCodeEnclosedTripleBackTicks(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.031 s  <<< FAILURE!
java.lang.AssertionError:
expected [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```] but found [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
] ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testInlineCodeEnclosedTripleBackTicks(MarkdownDocumentationTest.java:347)

[ERROR] testMultilineDocs(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.034 s  <<< FAILURE!
java.lang.AssertionError:
expected [description line 1
description line 2
description line 3] but found [description line 1
description line 2
]escription line 3
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testMultilineDocs(MarkdownDocumentationTest.java:420)

[ERROR] testMultiple(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.388 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Documentation for Tst struct] but found [Documentation for Tst struct
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testMultiple(MarkdownDocumentationTest.java:369)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
]ERROR]   MarkdownDocumentationTest.testDocAnnotation:56 expected [Documentation for Test annotation] but found [Documentation for Test annotation
]ERROR]   MarkdownDocumentationTest.testDocConnectorFunction:280 expected [Test Connector] but found [Test Connector
]ERROR]   MarkdownDocumentationTest.testDocConstant:78 expected [Documentation for testConst constant] but found [Documentation for testConst constant
]ERROR]   MarkdownDocumentationTest.testDocFiniteTypes:97 expected [Documentation for state enum] but found [Documentation for state enum
[ERROR]   MarkdownDocumentationTest.testDocFunction:154 expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
]SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`
[ERROR]   MarkdownDocumentationTest.testDocNativeFunction:396 expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
]SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`
]ERROR]   MarkdownDocumentationTest.testDocService:245 expected [PizzaService HTTP Service] but found [PizzaService HTTP Service
]ERROR]   MarkdownDocumentationTest.testDocType:132 expected [Documentation for Test type] but found [Documentation for Test type
[ERROR]   MarkdownDocumentationTest.testInlineCode:325 expected [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``] but found [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
] ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``
[ERROR]   MarkdownDocumentationTest.testInlineCodeEnclosedTripleBackTicks:347 expected [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```] but found [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
] ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```
[ERROR]   MarkdownDocumentationTest.testMultilineDocs:420 expected [description line 1
description line 2
description line 3] but found [description line 1
description line 2
]escription line 3
]ERROR]   MarkdownDocumentationTest.testMultiple:369 expected [Documentation for Tst struct] but found [Documentation for Tst struct
[INFO]
[ERROR] Tests run: 3401, Failures: 12, Errors: 0, Skipped: 0
```

**Comment by pranavan15** [comment]
@hasithaa 

The same test cases were passing for me. I tested in Windows 10. However, seems all these tests are failing for you as there are new lines appended at the end of the actual results, which are not there in the expected results. Now I trimmed all the actual results before asserting. Hope this fixes these issues.

**Comment by hasithaa** [comment]
@pranavan15 

Still getting following issues,

```
[ERROR] Tests run: 3401, Failures: 10, Errors: 0, Skipped: 0, Time elapsed: 447.564 s <<< FAILURE! - in TestSuite
[ERROR] testDocAnnotation(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.062 s  <<< FAILURE!
]ava.lang.AssertionError: expected [annotation `field a` documentation] but found [annotation `field a` documentation
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocAnnotation(MarkdownDocumentationTest.java:61)

[ERROR] testDocConnectorFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.032 s  <<< FAILURE!
]ava.lang.AssertionError: expected [url for endpoint] but found [url for endpoint
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocConnectorFunction(MarkdownDocumentationTest.java:285)

[ERROR] testDocFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.05 s  <<< FAILURE!
java.lang.AssertionError:
expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`]
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocFunction(MarkdownDocumentationTest.java:154)

[ERROR] testDocNativeFunction(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.AssertionError:
expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`]
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocNativeFunction(MarkdownDocumentationTest.java:396)

[ERROR] testDocService(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.301 s  <<< FAILURE!
]ava.lang.AssertionError: expected [Check orderPizza resource.] but found [Check orderPizza resource.
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocService(MarkdownDocumentationTest.java:249)

[ERROR] testDocType(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.016 s  <<< FAILURE!
]ava.lang.AssertionError: expected [type `field a` documentation] but found [type `field a` documentation
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testDocType(MarkdownDocumentationTest.java:137)

[ERROR] testInlineCode(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.AssertionError:
expected [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``] but found [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``]
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testInlineCode(MarkdownDocumentationTest.java:325)

[ERROR] testInlineCodeEnclosedTripleBackTicks(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError:
expected [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```] but found [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```]
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testInlineCodeEnclosedTripleBackTicks(MarkdownDocumentationTest.java:347)

[ERROR] testMultilineDocs(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.032 s  <<< FAILURE!
java.lang.AssertionError:
expected [description line 1
description line 2
description line 3] but found [description line 1
description line 2
description line 3]
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testMultilineDocs(MarkdownDocumentationTest.java:420)

[ERROR] testMultiple(org.ballerinalang.test.documentation.MarkdownDocumentationTest)  Time elapsed: 0.289 s  <<< FAILURE!
]ava.lang.AssertionError: expected [annotation `field a` documentation] but found [annotation `field a` documentation
        at org.ballerinalang.test.documentation.MarkdownDocumentationTest.testMultiple(MarkdownDocumentationTest.java:374)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
]ERROR]   MarkdownDocumentationTest.testDocAnnotation:61 expected [annotation `field a` documentation] but found [annotation `field a` documentation
]ERROR]   MarkdownDocumentationTest.testDocConnectorFunction:285 expected [url for endpoint] but found [url for endpoint
[ERROR]   MarkdownDocumentationTest.testDocFunction:154 expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that #foo will always be bigger than #bar.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`]
[ERROR]   MarkdownDocumentationTest.testDocNativeFunction:396 expected [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`] but found [Gets a access parameter value (`true` or `false`) for a given key. Please note that `foo` will always be bigger than `bar`.
Example:
`SymbolEnv pkgEnv = symbolEnter.packageEnvs.get(pkgNode.symbol);`]
]ERROR]   MarkdownDocumentationTest.testDocService:249 expected [Check orderPizza resource.] but found [Check orderPizza resource.
]ERROR]   MarkdownDocumentationTest.testDocType:137 expected [type `field a` documentation] but found [type `field a` documentation
[ERROR]   MarkdownDocumentationTest.testInlineCode:325 expected [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``] but found [Example of a string template:
  ``string s = string `hello {{name}}`;``

Example for an xml literal:
  ``xml x = xml `<{{tagName}}>hello</{{tagName}}>`;``]
[ERROR]   MarkdownDocumentationTest.testInlineCodeEnclosedTripleBackTicks:347 expected [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```] but found [Example of a string template:
  ```string s = string `hello {{name}}`;```
Example for an xml literal:
  ```xml x = xml `<{{tagName}}>hello</{{tagName}}>`;```]
[ERROR]   MarkdownDocumentationTest.testMultilineDocs:420 expected [description line 1
description line 2
description line 3] but found [description line 1
description line 2
description line 3]
]ERROR]   MarkdownDocumentationTest.testMultiple:374 expected [annotation `field a` documentation] but found [annotation `field a` documentation
[INFO]
[ERROR] Tests run: 3401, Failures: 10, Errors: 0, Skipped: 0
[INFO]
```

**Comment by pranavan15** [comment]
@hasithaa 

Identified the root cause for the above issues you got in 'MarkdownDocumentationTest' and fixed it. Those test cases were failing in Windows as because, in Windows env, line separator of files is "\r\n" whereas in Linux and Mac it is "\n". Fixed the failing tests by replacing the "\r" with "".

**Comment by pranavan15** [comment]
@hasithaa 

Regarding the commits messages, I have squashed some commits and reworded all other commits. Could you please check now?

**Comment by hasithaa** [comment]
Verified Build locally in Windows 10. Hence merging.

**Pull request merged**
