### PR TITLE
Fix query expression parsing inside other expressions

### LINKED ISSUE #33085: Cannot parse comma separated `query-expr` in the `list-constructor`
**Description:**
The following example cannot be parsed.

```bal
function init() {
    io:println(typeof [from int i in [1,2,3] select i*2, from int i in [1,2,3] where i % 2 != 0 select i]); // @output typedesc [int[],int[]]
}
```
With parenthisis for first query, following works.
```bal
function init() {
    io:println(typeof [(from int i in [1,2,3] select i*2), from int i in [1,2,3] where i % 2 != 0 select i]); // @output typedesc [int[],int[]]
}
```

### LINKED ISSUE #34333: Syntax error occurs when using a query expression as the initializer in a let expression.
**Steps to reproduce:**
```
PR projectedPR = let var projectedLables = from var {name} in firstPR.labels select {name} in {url:firstPR.url,title:firstPR.title, state: firstPR.state, created_at: firstPR.created_at, updated_at: firstPR.updated_at, merged_at: firstPR.merged_at, labels: projectedLables};
```

**Affected Versions:**
Swan Lake Beta6

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #34333
Fixes #33085 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by rdulmina — APPROVED** [review]

**Comment by rdulmina** [comment]
Shall we add `on` and `conflict` keywords to `isEndOfIntermediateClause`. I think they are missing.
https://github.com/ballerina-platform/ballerina-lang/blob/884f0c2038a04c09538f3e6f497957a909ad1223/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L11649

**Comment by lochana-chathura** [comment]
@rdulmina Those cases are handled already inside the `parseIntermediateClause()`. With null being returned, we break the loop. :)
https://github.com/ballerina-platform/ballerina-lang/blob/04f2c2ea37880970f26bb33ce15c10d7af1f4a8e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L11587-L11591

**Comment by rdulmina** [comment]
> @rdulmina Those cases are handled already inside the `parseIntermediateClause()`. With null being returned, we break the loop. :)
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/04f2c2ea37880970f26bb33ce15c10d7af1f4a8e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L11587-L11591

Yes, but ideally they should be in `isEndOfIntermediateClause` right?

**Comment by lochana-chathura** [comment]
> Yes, but ideally they should be in `isEndOfIntermediateClause` right?

Ah no. The reason we have handled them like that is the recovery in `parseIntermediateClause()`.
e.g.   `from int i in [1, 2] select i * 2 % on conflict ... `

the invalid `%` token get dropped in `parseIntermediateClause()` recovery. Those cases are not handled if we use them inside `isEndOfIntermediateClause()` right?

**Comment by rdulmina** [comment]
> > Yes, but ideally they should be in `isEndOfIntermediateClause` right?
> 
> Ah no. The reason we have handled them like that is the recovery in `parseIntermediateClause()`. e.g. `from int i in [1, 2] select i * 2 % on conflict ... `
> 
> the invalid `%` token get dropped in `parseIntermediateClause()` recovery. Those cases are not handled if we use them inside `isEndOfIntermediateClause()` right?

What I meant was ideally they should be in both methods :-)

**Review by rdulmina — APPROVED** [review]

**Comment by lochana-chathura** [comment]
Closing Temporary.

**Review by hasithaa — APPROVED** [review]

**Pull request merged**
