### PR TITLE
Increase timeout in strand dump test for `bal test`

### LINKED ISSUE #38676: [Bug]: StrandDumpTest.testStrandDumpDuringBalTest is failing intermittently
### Description

The test `StrandDumpTest.testStrandDumpDuringBalTest` is failing intermittently during PR builds. 
https://scans.gradle.com/s/t5dsxumapbwts

error log :
```
org.ballerinalang.test.context.BallerinaTestException: Failure to obtain the expected strand dump.	
Expected regular expression: Ballerina Strand Dump \[\d*/\d*/\d* \d*:\d*:\d*\]	
Obtained strand dump:	
Compiling source	
	testOrg/testPackageWithModules:0.1.0	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.verifyObtainedStrandDump(StrandDumpTest.java:174)	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.startProcessAndVerifyStrandDump(StrandDumpTest.java:154)	
at org.ballerinalang.test.troubleshoot.StrandDumpTest.testStrandDumpDuringBalTest(StrandDumpTest.java:92)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:566)	
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)	
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)	
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)	
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	
at java.util.concurrent.FutureTask.run(FutureTask.java:264)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
at java.lang.Thread.run(Thread.java:829)
```

### Steps to Reproduce

_No response_

### Affected Version(s)

current master

### OS, DB, other environment details and versions

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by Nadeeshan96**
$title
Fixes #38676

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Nadeeshan96** [comment]
Ran the build with tests in Ubuntu 7 times in the Github runner, the test did not intermittently fail.

**Review by HindujaB — APPROVED** [review]
LGTM

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Comment by warunalakshitha** [comment]
Shall we create an issue track to periodically check server start without waiting 30 seconds.

**Comment by Nadeeshan96** [comment]
> Shall we create an issue track to periodically check server start without waiting 30 seconds.

Created https://github.com/ballerina-platform/ballerina-lang/issues/38737.

**Pull request merged**
