### PR TITLE
[2201.4.x]Fix completions in named args with included record params context

### LINKED ISSUE #39296: [Bug]: No completion items for record fields of record typed named argument
### Description

image

The `secureSocket` argument is of the following type. 
```Ballerina
public type ListenerSecureSocket record {|
    crypto:KeyStore|CertKey key;
    record {|
        VerifyClient verifyClient = REQUIRE;
        crypto:TrustStore|string cert;
    |} mutualSsl?;
    record {|
        Protocol name;
        string[] versions = [];
    |} protocol?;
    record {|
        CertValidationType 'type = OCSP_STAPLING;
        int cacheSize;
        int cacheValidityPeriod;
    |} certValidation?;
    string[] ciphers = ["TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                        "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                        "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"];
    boolean shareSession = true;
    decimal handshakeTimeout?;
    decimal sessionTimeout?;
|};

```

The fields are not suggested as completion items. 

### Steps to Reproduce

Mentioned above

### Affected Version(s)

2201.3.2

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by malinthar**
## Purpose
$subject

Fixes #39296 

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]

**Comment by IMS94** [comment]
@malinthar seems like there are some test failures. Can you check?

**Comment by malinthar** [comment]
> @malinthar seems like there are some test failures. Can you check?

Seems like   https://github.com/ballerina-platform/ballerina-lang/pull/39404) is not available in the 2201.4.x branch yet. Shall we wait till the branches are synced or should we create a separate PR in the 2201.4.x branch?
@IMS94

**Comment by IMS94** [comment]
@malinthar Let's wait for 2201.4.0-stage to be synced to 2201.4.x

**Comment by IMS94** [comment]
@malinthar seems like the tests are still failing

**Comment by malinthar** [comment]
> @malinthar seems like the tests are still failing

This is because the branches are not synced yet https://github.com/ballerina-platform/ballerina-lang/pull/39481

**Review by IMS94 — APPROVED** [review]

**Pull request merged**
