### PR TITLE
[2201.2.x] Create path parameter symbols for name-less path parameters

### LINKED ISSUE #37669: [Bug]: Incorrect suggestion for resource path parameter without param name
### Description

1) Gives invalid suggestion `cl->/$*.accessor;` where it should suggest `cl->/[A].accessor;`

Screenshot from 2022-09-07 13-18-13

2) Suggest string value of constants; Suggests `cl->/["someLongPathSegment"].accessor;` where it should suggest `cl->/[A].accessor;`

Screenshot from 2022-09-07 13-23-01

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Labels

LanguageServer

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #37669

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by mohanvive** [comment]
@sanjana Do we need this for 2.x? If yes, can u open a PR to master as well?

**Comment by mohanvive** [comment]
> > @sanjana Do we need this for 2.x? If yes, can u open a PR to master as well?
> 
> @mohanvive Since this was originally intended to be applied in 2.x releases, sent a new PR to the master at #38146.

In that case, need one for 3.x as well.

**Comment by sanjana** [comment]
> > > @sanjana Do we need this for 2.x? If yes, can u open a PR to master as well?
> > 
> > 
> > @mohanvive Since this was originally intended to be applied in 2.x releases, sent a new PR to the master at #38146.
> 
> In that case, need one for 3.x as well.

@mohanvive sure. Created a PR for 3.x as well at: #38188

**Comment by sanjana** [comment]
Closing since fixes will be applied at #38146 and #38188.

**Pull request closed without merging**
