### PR TITLE
Fix ballerina lang issue 14981

### PR DESCRIPTION
**Pull request by praneesha**
## Purpose
This is to fix https://github.com/ballerina-platform/ballerina-lang/issues/14981.

Fixes #<Issue Number>

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by riyafa** [comment]
Shouldn't we review the bal files in the PR as well?

**Comment by praneesha** [comment]
@wggihan, should the BAL files be included in the doc review of this?

**Comment by wggihan** [comment]
> @wggihan, should the BAL files be included in the doc review of this?

Yes. Basically, we need to review under this location stdlib/jms/src/main/ballerina/jms/

**Comment by praneesha** [comment]
Reviewed the following BAL files in the stdlib/jms/src/main/ballerina/jms/ directory.

1. stdlib/jms/src/main/ballerina/jms/durable_topic_subscriber.bal
2. stdlib/jms/src/main/ballerina/jms/queue_receiver.bal
3. stdlib/jms/src/main/ballerina/jms/session.bal
4. stdlib/jms/src/main/ballerina/jms/topic_subscriber.bal

**Pull request merged**
