### PR TITLE
Improve log-api

### PR DESCRIPTION
**Pull request by MadhukaHarith92**
## Purpose
Improve existing api functions and add new api functions.

Fixes #<Issue Number>
https://github.com/ballerina-platform/ballerina-lang/issues/9285

## Approach
https://docs.google.com/document/d/1vU7-5Gkh2ZPH61ovLP5gGvfpPch54jnngC7AmNo1sX4/edit#heading=h.ptgufucu9qy0

### CODE REVIEW

**Comment by daneshk** [comment]
Shall we add test cases to cover all usecases

**Comment by MadhukaHarith92** [comment]
> Shall we add test cases to cover all use cases

Will be added in a separate PR : https://github.com/ballerina-platform/ballerina-lang/issues/23239

**Comment by pubudu91** [comment]
Were the APIs implemented in this PR agreed upon? The implemented APis are different from the ones proposed in the design doc and I don't see a mail thread in which these were agreed upon. In [1], @MaryamZi has raised some concerns regarding the APIs.

[1] [Ballerina Log API - Design](https://groups.google.com/forum/#!searchin/ballerina-dev/Ballerina$20Log$20API$20-$20Design%7Csort:date/ballerina-dev/ivZoGMVgvDA/qo05uRCsBwAJ)

**Comment by MadhukaHarith92** [comment]
> Were the APIs implemented in this PR agreed upon? The implemented APis are different from the ones proposed in the design doc and I don't see a mail thread in which these were agreed upon. In [1], @MaryamZi has raised some concerns regarding the APIs.
> 
> [1] [Ballerina Log API - Design](https://groups.google.com/forum/#!searchin/ballerina-dev/Ballerina$20Log$20API$20-$20Design%7Csort:date/ballerina-dev/ivZoGMVgvDA/qo05uRCsBwAJ)

Yes, we decided to implement APIs to log formatted strings (sprintDebug, sprintError, sprintInfo, sprintWarn, sprintTrace) based on the feedback from @MaryamZi.

In addition, setStrandLevelLog and setModuleLevelLog functions were not implemented yet because of blocking issues [[1]](https://github.com/ballerina-platform/ballerina-lang/issues/22931) & [[2]](https://github.com/ballerina-platform/ballerina-lang/issues/23001) respectively from the runtime.
[1] https://github.com/ballerina-platform/ballerina-lang/issues/22931
[2] https://github.com/ballerina-platform/ballerina-lang/issues/23001

**Comment by pubudu91** [comment]
I was referring to the changes to the existing log APIs, not the newly proposed functionality. In the design doc we are accepting `(any|error)...` but in this implementation we are changing it to `any`.

I think you have misunderstood what Maryam said. What she asked was why we are introducing a string formatter when we have string templates in the language itself. See [1].

Also

[1] [String Template Literal](https://ballerina.io/learn/by-example/string-template.html)

**Pull request closed without merging**
