### PR TITLE
Remove `Gson` library usage from the Profiler

### LINKED ISSUE #42900: [Improvement]: Remove the Gson Library usages in profiler tool
### Description

Then we can remove the packing gson library in runtime uber jar.

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### LINKED ISSUE #43073: [Improvement]: Replace Gson usages with io.runtime.api.JsonUtils and Refactor code in Profiler tool
### Description

Then we can remove Gson from ballerina rt.

### Describe your problem(s)

_No response_

### Describe your solution(s)

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by ravinperera00**
Fixes #43073 , Fixes #42900

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Shadow-Devil** [comment]
I think this also fixes #42900

**Comment by ravinperera00** [comment]
The code coverage for the PR is low because the functionality to be tested is under a shutdown hook. This problem is already tracked by https://github.com/ballerina-platform/ballerina-lang/issues/43071 as a separate issue.

**Comment by warunalakshitha** [comment]
Lets fix the merge conflicts and get this merge.

**Comment by Shadow-Devil** [comment]
It seems like the 
```
:language-server:language-server-core:test  
org.ballerinalang.langserver.diagnostics.CyclicDependenciesTest.testCyclicDependenciesOnOpen[1]
```
test is flaky, I also noticed it sometimes failing/succeeding in my PRs without any changes.

**Comment by warunalakshitha** [comment]
I am closing this since we have merge these changes with https://github.com/ballerina-platform/ballerina-lang/pull/43402.

**Pull request closed without merging**
