### PR TITLE
[Refactoring] Fix usage of rawtypes

### PR DESCRIPTION
**Pull request by Shadow-Devil**
## Purpose
To ensure type-safety, generics should always be filled out (= no more raw types).

Some issues I encountered:
- Some casts could not easily be made, like converting a `List<Object>` to a `List<String>`. For this I used the approach from [this Stackoverflow post](https://stackoverflow.com/questions/15427624/could-not-downcast-using-list-class-in-java) to cast `List<Object>` -> `List<?>` -> `List<String>`.
- Some generics can't be filled out since they are returned by a library or because of `ServiceLoader.load(Service.class)` which does not work with generics.
- In `TableValueImpl.entrySet()` there was a type error which I could only fix with a semantic change. But I think this was a bug.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by SasinduDilshara** [comment]
@Shadow-Devil seemslike there few conflicts in the PR branch, Can you look into that?

**Comment by SasinduDilshara** [comment]
@Shadow-Devil can you please resolve the conflicts in the PR?

**Comment by Shadow-Devil** [comment]
@SasinduDilshara Conflicts are resolved

**Comment by Shadow-Devil** [comment]
@SasinduDilshara will you be able to review this now that all checks have passed and no more conflicts are present?
Thank you in advance

**Review by SasinduDilshara — APPROVED** [review]

**Comment by Shadow-Devil** [comment]
There were some merge conflicts which I have resolved

**Comment by Shadow-Devil** [comment]
Could someone merge this please, since it was already approved for quite some time? Thank you in advance 😄

**Comment by Shadow-Devil** [comment]
Fixed merge conflicts via rebase

**Comment by Shadow-Devil** [comment]
With a very strange error:
```
The :jballerina-debugger-integration-test:jacocoMergeExec task failed.
Unable to read execution data file D:\a\ballerina-lang\ballerina-lang\tests\jballerina-debugger-integration-test\build\jacoco\debugger-runtime-test.exec
> (No message provided)
```
@gimantha Could you only restart the windows pipeline please?

**Review by NipunaRanasinghe — APPROVED** [review]
Bindgen tool, debugger and json-to-record converter related changes LGTM

**Review by gimantha — APPROVED** [review]

**Pull request merged**
