### PR TITLE
Fix inferred argument validation with type reference types

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$title.

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/39555

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]

**Review by hasithaa — APPROVED** [review]
Change Looks good to me.

**Comment by hasithaa** [comment]
@shafreenAnfar @chamil321 With this PR http module is breaking. Looks like we used a bug as a feature. Shall we fix it?

**Comment by MaryamZi** [comment]
> @shafreenAnfar @chamil321 With this PR http module is breaking. Looks like we used a bug as a feature. Shall we fix it?

The error is for https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_request_context.bal#L88. The inferred part of the union and the remaining members have to be disjoint in order to be able to figure out the part of the type corresponding to inference. This particular line fails because `value:Cloneable` includes `error` and therefore isn't disjoint with `ListenerError`. 

Similar code

```ballerina
import ballerina/lang.value;

public type ReqCtxMember value:Cloneable|isolated object {};

public type ReqCtxMemberType typedesc<ReqCtxMember>;

function f1(string key, ReqCtxMemberType targetType = <>) returns targetType|error = external; // now an error

function f2(string key, typedesc<value:Cloneable|isolated object {}> targetType = <>) returns targetType|error = external; // already an error
```

**Comment by TharmiganK** [comment]
> > > @shafreenAnfar @chamil321 With this PR http module is breaking. Looks like we used a bug as a feature. Shall we fix it?
> > 
> > 
> > The error is for https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_request_context.bal#L88. The inferred part of the union and the remaining members have to be disjoint in order to be able to figure out the part of the type corresponding to inference. This particular line fails because `value:Cloneable` includes `error` and therefore isn't disjoint with `ListenerError`.
> > Similar code
> > ```ballerina
> > import ballerina/lang.value;
> > 
> > public type ReqCtxMember value:Cloneable|isolated object {};
> > 
> > public type ReqCtxMemberType typedesc<ReqCtxMember>;
> > 
> > function f1(string key, ReqCtxMemberType targetType = <>) returns targetType|error = external; // now an error
> > 
> > function f2(string key, typedesc<value:Cloneable|isolated object {}> targetType = <>) returns targetType|error = external; // already an error
> > ```
> 
> @TharmiganK Please note

Ack, will fix this 👍

**Review by dulajdilshan — APPROVED** [review]

**Review by IMS94 — APPROVED** [review]
LGTM!

**Pull request merged**
