### PR TITLE
[2201.2.x] Fix missing quote in completion item for keywords in annotation completions

### LINKED ISSUE #37769: [Bug]: Single quote prefix is not added to `class` field name during autocompletion
### Description

$title

autocompletion

### Steps to Reproduce

```bal
import ballerina/jballerina.java;

function func() = @java:Method {
    'class: ""
} external;
```

### Affected Version(s)

Ballerina 2201.2.0 (Swan Lake Update 2)
VSCode plugin version v3.0.2

### OS, DB, other environment details and versions

_No response_

### Related area

Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #37769 

Screenshot 2022-09-30 at 11 16 48

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]

**Comment by mohanvive** [comment]
> @gayalkuruppu shall we send this to 2201.3.x instead?

@gayalkuruppu shall we do this?

**Comment by IMS94** [comment]
Closing this since in favor of https://github.com/ballerina-platform/ballerina-lang/pull/38043 which was sent to master

**Comment by IMS94** [comment]
Reopened until the PR for 2201.3.x is sent

**Comment by IMS94** [comment]
Sent to 2201.3.x with #38242

**Pull request closed without merging**
