### PR TITLE
Add completion support for annotation access expression

### LINKED ISSUE #32843: Add completion support for annotation access expression
**Description:**
$Title

### PR DESCRIPTION
**Pull request by gayalkuruppu**
Fixes #32843

## Samples

**For,**

1. Functions

https://user-images.githubusercontent.com/46120162/139941525-17c46027-cbfc-4a65-8fe2-bf02a303ab88.mov

2. Services

https://user-images.githubusercontent.com/46120162/139941544-6ab911b2-52f5-4ea3-b0fd-6440b94de062.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by nadeeshaan** [comment]
Can we verify some more use-cases here? For example, in the case of record-type-descriptors and etc?

**Review by nadeeshaan — CHANGES_REQUESTED** [review]
Shall we support the following as well?
`module1:AnnotationType? unionResult = typedescResult.@<cursor>`
at the cursor, we should get the completions for modules

**Comment by nadeeshaan** [comment]
Shall we sort the completions as well?

**Comment by gayalkuruppu** [comment]
> Shall we support the following as well? `module1:AnnotationType? unionResult = typedescResult.@<cursor>` at the cursor, we should get the completions for modules

Done

**Comment by gayalkuruppu** [comment]
> Shall we sort the completions as well?

Done

**Review by nadeeshaan — APPROVED** [review]
LGTM

**Pull request merged**
