### PR TITLE
Set compiler plugin cache `getData` api to package private

### PR DESCRIPTION
**Pull request by Thevakumar-Luheerathan**
## Purpose
Related to #42291

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
If `getData` is protected, why not make `putData` protected as well?

**Comment by Thevakumar-Luheerathan** [comment]
> If `getData` is protected, why not make `putData` protected as well?

Some tool implementation(Scanner tool by @Xenowa) uses that to pass the data to compiler plugin side.

**Review by Dilhasha — APPROVED** [review]

**Comment by hasithaa** [comment]
> > If `getData` is protected, why not make `putData` protected as well?
> 
> Some tool implementation(Scanner tool by @Xenowa) uses that to pass the data to compiler plugin side.

@Xenova Can you share your use-case?

**Comment by Xenowa** [comment]
> > > If `getData` is protected, why not make `putData` protected as well?
> > 
> > 
> > Some tool implementation(Scanner tool by @Xenowa) uses that to pass the data to compiler plugin side.
> 
> @Xenowa Can you share your use-case?

Having an API for passing a context from Ballerina scan tool to compiler plugins allows for extending the static code analysis functionalities of the tool. By passing a scanner context created by the scan tool, compiler plugins can directly report issues through this context without the need for intermediate file-based I/O.

Currently, to obtain issues reported via static code analysis done by compiler plugins, a write of the analysis issues to a file from the compiler plugin side and a read from the scan tool side are performed.

**Pull request merged**
