### PR TITLE
Fix issue with defining empty closed records

### LINKED ISSUE #14748: Unable to define an empty sealed record
**Description:**
Cannot seal a record with no fields. 

**Steps to reproduce:**
```ballerina
public type ExposeConfig record {||};
```

Output:
`error: ballerinax/docker:0.0.0::annotation.bal:71:34: invalid token '||'`

**Affected Versions:**
0.990.4-SNAPSHOT

**OS, DB, other environment details and versions:**
MAC

### LINKED ISSUE #15129: [Spec Deviation] Update record type descriptors as inclusive and exclusive record type descriptors
Record type descriptor grammar has changed slightly with the introduction of inclusive record type descriptors and exclusive record type descriptors. 
```
record-type-descriptor := inclusive-record-type-descriptor | exclusive-record-type-descriptor
inclusive-record-type-descriptor :=  record { field-descriptor* }
exclusive-record-type-descriptor :=  record {| field-descriptor* [record-rest-descriptor] |}
```
A record type descriptor that either is an inclusive-record-type-descriptor or is an exclusive-record-type-descriptor with a record-rest-descriptor is called open; a record type descriptor that is not open is called closed.

A type descriptor record { F }; is equivalent to record {| F; (anydata|error)...; |},

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #14748 
Fixes #15129 

## Samples
```ballerina
type Foo record {||};

type Bar1 record { ||}; // compile error

type Bar2 record {|| }; // compile error
```

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Required Balo version update
- [ ] Updated Change Log
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
@pubudu91 Shall we fix the new grammar changes as well included in #15129?

**Comment by hasithaa** [comment]
@pubudu91 Since @NipunaMarcus looking in this, shall we mark this as WIP ?

**Comment by NipunaMarcus** [comment]
@hasithaa +1 for making this WIP ...

**Comment by NipunaMarcus** [comment]
@pubudu91 .. so when we define a sealed record for a specific type following is how we did earlier, 
```
type Person record {
    string name;
    int id;
   string...;
}
```
Now with the new changes, this has to be defined as below?
```
type Person record {|
    string name;
    int id;
    string...;
|}
```
Is this correct?

**Comment by pubudu91** [comment]
Yes, that’s correct

**Comment by hasithaa** [comment]
@pubudu538 Can you check the build failure?

**Comment by pubudu91** [comment]
Yeah looking in to it.. It was in examples test. Ran it through Maven and nothing failed. Retriggered Travis and running a local Gradle build as well to see

**Pull request merged**
