### PR TITLE
[Refactoring] Replace full qualifier with import

### PR DESCRIPTION
**Pull request by Shadow-Devil**
## Purpose
Replaces `some.package.Class` with `import some.packe;` and directly using `Class`.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by Shadow-Devil** [comment]
I don't really understand why the `Build Stdlib Level (6)` pipeline fails, since this change should be trivial.

**Comment by Shadow-Devil** [comment]
Could someone please review this? (also commenting to remove stale status)

**Review by MaryamZi — COMMENTED** [review]
@Shadow-Devil, could you please sync/rebase the changes with the upstream branch? Sorry about the delay in getting this reviewed, and therefore, having to sync.

The rest of the changes LGTM. I've requested a few more reviews only because there are some codecov warnings (not due to changes in this PR of course), but we should be able to merge soon.

**Review by NipunaRanasinghe — COMMENTED** [review]
Debugger related changes LGTM

**Review by MaryamZi — APPROVED** [review]

**Comment by KavinduZoysa** [comment]
LS-related changes are verified. LGTM

**Review by azinneera — APPROVED** [review]

**Review by NipunaMadhushan — APPROVED** [review]

**Comment by MaryamZi** [comment]
@Shadow-Devil, could you please sync/rebase the changes with the upstream branch again? Sorry about the inconvenience.

**Review by NipunaRanasinghe — APPROVED** [review]

**Comment by Shadow-Devil** [comment]
@MaryamZi I just rebased this branch onto master

**Comment by MaryamZi** [comment]
> @MaryamZi I just rebased this branch onto master

Thank you. I'm afraid there are conflicts now though, could you please resolve them too?

**Comment by Shadow-Devil** [comment]
@MaryamZi no problem, they should be fixed now

**Review by MaryamZi — APPROVED** [review]
Thank you!

**Review by NipunaRanasinghe — APPROVED** [review]

**Pull request merged**
