### PR TITLE
Add validation for @subgraph:Entity stub entities

### PR DESCRIPTION
**Pull request by Codewithsumeet**
Fixes https://github.com/ballerina-platform/ballerina-library/issues/4816

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by gimantha** [comment]
Hi @Codewithsumeet, Welcome!,
I believe you are trying to add validation for subgraph annotation in graphQL.  The right place to raise a PR or issue related to graphQL is https://github.com/ballerina-platform/module-ballerina-graphql repository. Let's create an issue first if you face any problem., then work on the solution.

**Comment by Codewithsumeet** [comment]
@gimantha actually i was working on the issue of adding the compile time error which i was assigned

**Comment by gimantha** [comment]
> > @gimantha actually i was working on the issue of adding the compile time error which i was assigned
> 
> Can you point that issue?

found it: https://github.com/orgs/ballerina-platform/projects/376/views/2

**Comment by gimantha** [comment]
@DimuthuMadushan @ThisaruGuruge @MohamedSabthar I hope this should be a compiler plugin in graphQL repo right? We cannot directly add it to the Ballerina compiler

**Comment by DimuthuMadushan** [comment]
Hi @Codewithsumeet, This change should be made in the [compiler plugin](https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler) of the GraphQL module. You can refer to the [service validation](https://github.com/ballerina-platform/module-ballerina-graphql/tree/master/compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/service/validator) in the GraphQL compiler plugin for guidance.

**Comment by gimantha** [comment]
@Codewithsumeet Please refer to @DimuthuMadushan 's comment. We will close this pull request hence the related repo for this task is [ballerina-lang ](https://github.com/ballerina-platform/ballerina-lang)

**Comment by Codewithsumeet** [comment]
okayy

**Comment by Codewithsumeet** [comment]
@gimantha @DimuthuMadushan i have made changes in the compiler plugin accordingly please check it out!

**Pull request closed without merging**
