### PR TITLE
Wrap working dir path with quotes

### LINKED ISSUE #34496: Bal CLI  fails when a cmd is invoked from a folder which has spaces in name
**Description:**
When we execute a bal cmd (e.g. ```bal home```) from a folder which has spaces in its name, bal script passes invalid arguments to JVM as it hasn't wrapped the heapdump path with quotes and it fails. 

**Steps to reproduce:**

Capture

Capture2

**Steps to fix:**

Capture3

Capture4

**Affected Versions:**
slbeta6

**Related Issues (optional):**
This is the same reason why VSCode extension fails on windows with WSL2.  In that setup, the working directory has spaces in its name (```c:/...../AppData/.../Microsoft VS Code```) and hence same issue happens. This is critical as most windows users are now using WSL.
https://github.com/ballerina-platform/ballerina-lang/issues/33305
https://github.com/wso2/ballerina-plugin-vscode/issues/136

**Suggested Labels (optional):**
Severity/Critical

### PR DESCRIPTION
**Pull request by kaviththiranga**
## Purpose
This is to prevent invalid arguments being passed into JVM
when the cwd has spaces in its name.

Fixes #34496

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by NipunaMadhushan** [comment]
@kaviththiranga I checked the changes in Ubuntu, CentOS and MacOS. Heap dumps are generated without causing any error.

**Review by keizer619 — APPROVED** [review]

**Comment by keizer619** [comment]
@NipunaMadhushan @kaviththiranga Shall we send this to `stage-swan-lake-rc1` branch as we do release on that branch

**Comment by kaviththiranga** [comment]
@keizer619 changed the branch

**Comment by kaviththiranga** [comment]
Closing this as the fix is already sent in another commit.

**Pull request closed without merging**
