### PR TITLE
Add parameter defaultability information to resource function type

### PR DESCRIPTION
**Pull request by rdhananjaya**
## Purpose
Add parameter defaultability information to resource function type.

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/27417

Related issue to add these extra info to BIR https://github.com/ballerina-platform/ballerina-lang/issues/27408

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by ThisaruGuruge** [comment]
Is there a way to get the default value, if a parameter is a defaultable one?

**Comment by rdhananjaya** [comment]
> Is there a way to get the default value, if a parameter is a defaultable one?

With current implementation, we can't do that as we code generate the default values inside the function.

**Comment by ThisaruGuruge** [comment]
> > Is there a way to get the default value, if a parameter is a defaultable one?
> 
> With current implementation, we can't do that as we code generate the default values inside the function.

For the GraphQL implementation, we need this information. GraphQL introspection should be able to show the default value of an argument when an introspection query requests it.

**Review by KavinduZoysa — DISMISSED** [review]

**Comment by KavinduZoysa** [comment]
Shall we update the PR?

**Review by KavinduZoysa — APPROVED** [review]

**Pull request merged**
