### PR TITLE
Improve ExpectedTypeFinder on specific field nodes

### LINKED ISSUE #39378: [Bug]: Inaccurate expected type provided by expected type API
### Description

As mentioned in the https://github.com/ballerina-platform/ballerina-lang/issues/39296#issuecomment-1399898536 expected type provided at the cursor position is inaccurate.

```ballerina
import ballerina/http;

listener http:Listener securedEp = new (9090, secureSocket = {'key: {<cursor>}})
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject 

Fixes #39378

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by malinthar — CHANGES_REQUESTED** [review]
Shall we add a test case in the semantic API side

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Review by DamithaSenevirathne — DISMISSED** [review]
LGTM

**Comment by IMS94** [comment]
@malinthar I could not reproduce this on a ballerina source without using a standard library. That's why I didn't add a test case.

**Comment by malinthar** [comment]
> @malinthar I could not reproduce this on a ballerina source without using a standard library. That's why I didn't add a test case.

Could you try this? 
```Ballerina
public type KeyStore record {|
    string path;
    string password;
|};

public type Key record {|
    string privateKey;
    string pubicCert;
|};

public type SecureSocket record {|
    KeyStore|Key key;
    string protocol;
    string auth?;
|};

public type Config record {|
    SecureSocket secureSocket?;
    int timeout = 60;
    string 'version = "2.0";
|};

public class ExtendedListener {

    private int port = 0;

    public function init(int port, *Config config) returns error? {

    }

    public function 'start() returns error? {
        return self.startEndpoint();
    }

    public function gracefulStop() returns error? {
        return ();
    }

    public function immediateStop() returns error? {
        error err = error("not implemented");
        return err;
    }

    public function attach(service object {} s, string[]|string? name = ()) returns error? {
        return self.register(s, name);
    }

    public function detach(service object {} s) returns error? {
        return ();
    }



    public function initEndpoint() returns error? {
        return ();
    }

    function register(service object {} s, string[]|string? name) returns error? {
        return ();
    }

    function startEndpoint() returns error? {
        return ();
    }
}

public listener li =  new ExtendedListener(9090,  secureSocket = {key:{});
```

**Comment by IMS94** [comment]
@malinthar thanks! Added a test case.

**Review by malinthar — APPROVED** [review]

**Pull request merged**
