### PR TITLE
Add Change log to the repo

### PR DESCRIPTION
**Pull request by anupama-pathirage**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Even this pr add md file , code coverage seems to be decreased by 3.79% based on codecov report.  shall we check why it is shown like that?

**Comment by anupama-pathirage** [comment]
@Phans Can you have any input on this decrease in code coverage? I guess this is due to incomplete PR merge previously

**Comment by roonyh** [comment]
Some reasons are documented [here](https://docs.codecov.io/docs/unexpected-coverage-changes#section-reasons-for-unexpected-changes)

So in addition to reports not being uploaded, I think we might have tests with nondeterministic code paths. That is, some tests may pass, the actual code that gets called is different. They may depend on time or thread scheduling or something. This is just a guess. :)

If everyone can take a look at the diff of codecov for this PR maybe someone can identify why this particular code may be called only sometimes.

https://codecov.io/gh/ballerina-platform/ballerina-lang/pull/14246/changes

**Comment by riyafa** [comment]
Can we also explain the purpose of each of these categories? Then anyone who is creating a PR knows what to include under these sections.

**Comment by pahans** [comment]
@anupama-pathirage The reason is not "reports not being uploaded" because previous commit is [successfully completed ](https://codecov.io/gh/ballerina-platform/ballerina-lang/pull/14246/commits). As @roonyh said it could be  tests with nondeterministic code paths.

**Comment by anupama-pathirage** [comment]
> Can we also explain the purpose of each of these categories? Then anyone who is creating a PR knows what to include under these sections.

@riyafa Updated the description with more details. No point in add a description under each section, as it will go away with the first line.

**Pull request merged**
