### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TylerJewell**
Modified the opening paragraphs to match what is on the home page of ballerina.io - this is the refined, shorter version of the value prop.

### CODE REVIEW

**Comment by TylerJewell** [comment]
@samgnaniah - if this PR gets approved, please update the readme for all of our other repos, too. I presume that they all have the same opening statements about Ballerina as this one, and then after the summary, they divert into repo-specific discussions?

**Comment by samgnaniah** [comment]
@TylerJewell - Ack. Will do.

**Comment by hasithaa** [comment]
@samgnaniah I have merged this PR.

**Comment by samgnaniah** [comment]
@hasithaa - Ack. Thanks for checking this.

**Pull request merged**
