### PR TITLE
Add completions for configurable qualifier

### LINKED ISSUE #35953: Completions not appears for type-descriptor in existing module var decl statement with configurable qualifier
**Description:**

**Steps to reproduce:**
Try to get completions for the type-descriptor in existing module-var-decl statement with configurable qualifier

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)
Language specification 2022R1

### PR DESCRIPTION
**Pull request by mindula**
## Purpose
This PR adds completions for configurable qualifier.

Fixes #35953

## Samples
https://user-images.githubusercontent.com/61020198/168987979-34647021-1b9e-4168-9831-e51757444ade.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gayalkuruppu — COMMENTED** [review]
Shall we add another test case and explore,
```
configurable <cursor>
```
It routes to `ModulePartNodeContext` and gets `getModulePartContextItems(context)` completions which also includes completions like snippet for `public main function() {}` which I believe are wrong. WDYT?

**Comment by mindula** [comment]
> Shall we add another test case and explore,
> 
> ```
> configurable <cursor>
> ```
> 
> It routes to `ModulePartNodeContext` and gets `getModulePartContextItems(context)` completions which also includes completions like snippet for `public main function() {}` which I believe are wrong. WDYT?

Those completions are given when there's a following type of scenario. 
```
configurable <cursor>

public function main() {
    
}
``` 
Either way this should be fixed. Will look into it

**Comment by mindula** [comment]
> Shall we add another test case and explore,
> 
> ```
> configurable <cursor>
> ```
> 
> It routes to `ModulePartNodeContext` and gets `getModulePartContextItems(context)` completions which also includes completions like snippet for `public main function() {}` which I believe are wrong. WDYT?

Can be resolved once #36215 is fixed

**Comment by gayalkuruppu** [comment]
> > Shall we add another test case and explore,
> > ```
> > configurable <cursor>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It routes to `ModulePartNodeContext` and gets `getModulePartContextItems(context)` completions which also includes completions like snippet for `public main function() {}` which I believe are wrong. WDYT?
> 
> Those completions are given when there's a following type of scenario.
> 
> ```
> configurable <cursor>
> 
> public function main() {
>     
> }
> ```
> 
> Either way this should be fixed. Will look into it

Your example is a different scenario. Parser identifies my initial example correctly as, and 
```
configurable 
 MISSING[] MISSING[] MISSING[=] MISSING[?] MISSING[;]
```
will have to handle this.

**Review by IMS94 — APPROVED** [review]

**Comment by IMS94** [comment]
> > Shall we add another test case and explore,
> > ```
> > configurable <cursor>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It routes to `ModulePartNodeContext` and gets `getModulePartContextItems(context)` completions which also includes completions like snippet for `public main function() {}` which I believe are wrong. WDYT?
> 
> Those completions are given when there's a following type of scenario.
> 
> ```
> configurable <cursor>
> 
> public function main() {
>     
> }
> ```
> 
> Either way this should be fixed. Will look into it

The above case will be fixed with #36323

**Pull request merged**
