### PR TITLE
Remove Streaming type and its dependencies

### LINKED ISSUE #20653: Remove Streaming type and its dependencies.
As a preparation for the new Stream type implementation, We are removing old streaming implementation from the Master.

### PR DESCRIPTION
**Pull request by grainier**
## Purpose
$title

Fixes #20653

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by grainier** [comment]
- @nadeeshaan, @NipunaMarcus could you please review and verify LS related changes?
- @NipunaRanasinghe This changes Parser and Lexer, could you please migrate them to idea plugin as well?

**Comment by nadeeshaan** [comment]
> * @nadeeshaan, @NipunaMarcus could you please review and verify LS related changes?
> * @NipunaRanasinghe This changes Parser and Lexer, could you please migrate them to idea plugin as well?

Regarding the Language Server, streaming type is reflected through the symbol tables and when removed those will not be shown

**Comment by NipunaRanasinghe** [comment]
> * @nadeeshaan, @NipunaMarcus could you please review and verify LS related changes?
> * @NipunaRanasinghe This changes Parser and Lexer, could you please migrate them to idea plugin as well?

@grainier Ack, will do! BTW will these changes be merged into ballerina-1.1.x as well? (As this is an API change, I guess not)

**Comment by grainier** [comment]
> > * @nadeeshaan, @NipunaMarcus could you please review and verify LS related changes?
> > * @NipunaRanasinghe This changes Parser and Lexer, could you please migrate them to idea plugin as well?
> 
> @grainier Ack, will do! BTW will these changes be merged into ballerina-1.1.x as well? (As this is an API change, I guess not)

No, this will only affect 1.2.0 (current master)

**Pull request merged**
