### PR TITLE
Add endpoint detection for init outside the document

### PR DESCRIPTION
**Pull request by NipunaMarcus**
## Purpose
 - Add endpoint detection for init outside the document

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
@NipunaMarcus There are conflits.

**Comment by NipunaMarcus** [comment]
> @NipunaMarcus There are conflits.

checking now

**Review by hevayo — CHANGES_REQUESTED** [review]
Can you send the pr from the stage branch

**Comment by NipunaMarcus** [comment]
will send another PR to this branch

**Comment by NipunaMarcus** [comment]
let's keep this for master

**Comment by nadeeshaan** [comment]
Since we have a PR for the stage branch shall we close this one?

**Pull request closed without merging**
