### PR TITLE
Introduce API to retrieve stored properties in the strand

### PR DESCRIPTION
**Pull request by chamil321**
## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by manuranga** [comment]
If people can't write ballerina programs without having access to low level access Ballerina internal, it's big issue. We should try and get rid of Strand hacks, not improve them. Better to discuss this kind of thing with a lager audience, how about ballerina spec repo?

**Comment by manuranga** [comment]
Maybe what this shows is ballerina language need support for thread locals ?

**Comment by chamil321** [comment]
> If people can't write ballerina programs without having access to low level access Ballerina internal, it's big issue. We should try and get rid of Strand hacks, not improve them. Better to discuss this kind of thing with a lager audience, how about ballerina spec repo?

Agree to consider this as a ballerina requirement. Because thread local variable are quite important aspect.

Ideally there should be a proper way from the runtime to propagate thread local variable from the parent strand to the child strand. The PR ballerina-platform/ballerina-lang#31466 is a new API to access the complete property map and pass it over. That will reduce the cost of access each property and setting it back like the improvement done in the ballerina-platform/module-ballerina-http#496

But it's better if they provide propagation from the runtime.
case 1: When ballerina thread start, i.e invoke resource function from java, properties has to be passed
case 2: When another thread start after a parent thread execution, parent properties are propagated internally

However I'll create an issue on the spec repo.

**Comment by manuranga** [comment]
I understand that there are issues with current implementation, maybe we can improve it until we have a proper solution, but I don't think we should make it even bigger. If you look at the ballerina spec, it doesn't even have a concept of Strand parent, so I feel like what we have done is a spec violation.

So we first need a spec issues justifying having a parent strand concept and being able pass though it. Let's describe the basic requirement without getting into our implementation.

**Comment by anupama-pathirage** [comment]
@chamil321 / @shafreenAnfar Do we need this PR? Looks like it got automatically closed without any attention. If you really don't need this PR anymore, please remove the `stale` label from the PR. Then it won't get added to the `[Stale PR] Ballerina Stale PR Details` mail in the future.

**Pull request closed without merging**
