### PR TITLE
Remove old context resolvers and the ANTLR based resolving

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by JobaDiniz** [comment]
I came from [Build your own programming language with ANTLR](https://shalithasuranga.medium.com/build-your-own-programming-language-with-antlr-5201955537a5) which mentions `Ballerina` as a project that uses ANTLR. However it seems this project is using something else, I'm just curious if there is a discussion of why you guys made such decision.

**Comment by nadeeshaan** [comment]
@JobaDiniz Instead of using ANTLR as the parser, we used our own implementation of the parser, for Ballerina. One of the main reasons behind the decision was that the ANTLR parser was not context sensitive enough for the Language Server implementation. When there are multiple errors in a given source, identifying the contexts for providing language features such as code completions were difficult.

Also, the with our implementation we got the flexibility to manage the syntax tree by introducing cleaner parser APIs as well.

**Comment by JobaDiniz** [comment]
So it’s not possible to use your parser for other languages as it’s implemented only for Ballerina?

I’ve seen the 1.3 version in comparison with the 2.0 and it’s way cleaner the classes and parser analyzer

**Comment by nadeeshaan** [comment]
@JobaDiniz yes, this implementation is specific to Ballerina. But, the concept can be implemented for other languages as well. We also have a toml parser implemented reusing this concept.

**Pull request merged**
