### PR TITLE
Read annotation attachments of functions and type-definitions in BIR

### LINKED ISSUE #30222: Annotations are ignored when reading a BIR
Currently we seem to be skipping the annotations when reading a BIR. I suspect this is because we currently don't have a way of modeling/representing annotation values when read from a BIR.

### LINKED ISSUE #33711: Semantic API doesn't contains annotations of the modules pulled by central
**Description:**
$Subject. 
However semantic api works just fine, when the module is in the same package(as a module)
image

When the module is pushed to the central (or local repo), semantic api does not return the annotations.
**Steps to reproduce:**
Working code - https://github.com/ballerina-platform/module-ballerina-c2c/tree/master/c2c-extension-test/src/test/resources/service/expose-int-or-http

Module Code - https://github.com/ballerina-platform/module-ballerina-c2c/blob/master/c2c-extension-test/src/test/resources/service/expose-int-or-http/modules/mod/mod.bal#L21

**Affected Versions:**
slbeta3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #33711
Fixes #30222 

## Approach
Read the annotations from the BIR and generate the symbols.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
Could you please add test cases ?

**Review by MaryamZi — COMMENTED** [review]
@dulajdilshan, we've also started looking into fixing https://github.com/ballerina-platform/ballerina-lang/issues/16379 in general. Shall we wait for a conclusion on the points raised there before merging this PR, since what's included in the BIR may change?

**Comment by pcnfernando** [comment]
If we are waiting on https://github.com/ballerina-platform/ballerina-lang/issues/16379, shall we close this and reopen if needed @dulajdilshan

**Comment by dulajdilshan** [comment]
Closing this as invalid for now

**Pull request closed without merging**
