### PR TITLE
Fix completion within the let expression node context

### LINKED ISSUE #33475: Wrong completions inside binary expressions in let expression
**Description:**
We get `in` keyword inside binary expressions in let expression where as we should get expression completions

**Steps to reproduce:**
```
function test(float a) returns float {
    return let float b = a + <cursor>
}
```

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #33475

## Approach
- Introduce a visitor to capture the complete expressions

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by gayalkuruppu** [comment]
Not sure whether this scenario is within the scope of this PR, but can we add `in` keyword completion for the following scenario?

Screenshot 2021-11-08 at 16 52 40

**Review by malinthar — DISMISSED** [review]
LGTM

**Review by IMS94 — DISMISSED** [review]

**Comment by mohanvive** [comment]
@nadeeshaan Any reason to mark this as draft?

**Comment by nadeeshaan** [comment]
> @nadeeshaan Any reason to mark this as draft?

@mohanvive there are couple of changes to be done for the use-case raised by @gayalkuruppu and will be ready for review once done

**Review by mohanvive — APPROVED** [review]

**Pull request merged**
