### PR TITLE
Fix clearing the diagnostics of a deleted source file

### LINKED ISSUE #34903: Deleting a source file doesn't clear diagnostics of that file
**Description:**

Create a ballerina project. Add another `bal` file and type something invalid there. In VSCode, under the `problems` tab, you will see errors related to that newly created file. 

Now, delete the new file and look at the `Problems` tab. Diagnostics are still there.

**Steps to reproduce:**
See description

**Affected Versions:**
Swan Lake 2201 GA

### PR DESCRIPTION
**Pull request by TharushiJay**
## Purpose
This PR adds a fix to clear the diagnostics when a `.bal` file or a module is deleted.

Fixes #34903

## Approach
Obtained the project path using `projectOfWatchedFileChange()` to publish the diagnostics.

## Samples
https://user-images.githubusercontent.com/27485094/162436933-518a0573-494f-4f0c-b40b-65662503553b.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by mohanvive** [comment]
@TharushiJay It seems there is a test failure, shall we please check this?

**Comment by TharushiJay** [comment]
> @TharushiJay It seems there is a test failure, shall we please check this?

Looked into it. The tests are failing with `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"`. They're not related to this PR. Seems like there's quite a few other PRs failing with the same error as well.

**Comment by mohanvive** [comment]
> > @TharushiJay It seems there is a test failure, shall we please check this?
> 
> Looked into it. The tests are failing with `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"`. I think they're not related to this PR. Seems like there's quite a few other PRs (35755, 35723) failing with the same error as well.

It seems below test case failing

language-server-core-test-suite > language-server-core-tests > org.ballerinalang.langserver.completion.StatementContextTest > test[45](onfail_clause_ctx_config2c.json, statement_context) FAILED
    java.lang.AssertionError: Failed Test for: completion/statement_context/config/onfail_clause_ctx_config2c.json
        at org.testng.Assert.fail(Assert.java:96)
        at org.ballerinalang.langserver.completion.CompletionTest.test(CompletionTest.java:75)
        at org.ballerinalang.langserver.completion.StatementContextTest.test(StatementContextTest.java:39)

**Comment by TharushiJay** [comment]
> > > @TharushiJay It seems there is a test failure, shall we please check this?
> > 
> > 
> > Looked into it. The tests are failing with `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"`. I think they're not related to this PR. Seems like there's quite a few other PRs (35755, 35723) failing with the same error as well.
> 
> It seems below test case failing
> 
> language-server-core-test-suite > language-server-core-tests > org.ballerinalang.langserver.completion.StatementContextTest > test[45](onfail_clause_ctx_config2c.json, statement_context) FAILED java.lang.AssertionError: Failed Test for: completion/statement_context/config/onfail_clause_ctx_config2c.json at org.testng.Assert.fail(Assert.java:96) at org.ballerinalang.langserver.completion.CompletionTest.test(CompletionTest.java:75) at org.ballerinalang.langserver.completion.StatementContextTest.test(StatementContextTest.java:39)

This has been failing in `2201.0.x`. I've fixed it in this PR. Maybe @malinthar can verify the test change?

**Review by mohanvive — APPROVED** [review]
Please change the base to 2201.0.3-stage-new.

**Comment by mohanvive** [comment]
New PR, https://github.com/ballerina-platform/ballerina-lang/pull/35771

**Pull request closed without merging**
