### PR TITLE
Fix config passing in build and test commands

### LINKED ISSUE #18830: Config file cannot be given to build and test commands
With the recent changes to how configs are passed, it doesn't seem to work with build and test commands
```
$ ballerina test recs --b7a.config.file=bal.conf
ballerina: unknown option: '--b7a.config.file=bal.conf'
Run 'ballerina help' for usage.
```

### PR DESCRIPTION
**Pull request by pubudu91**
Fixes #18830

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Shall we add some tests. May be we can add after release.

**Comment by warunalakshitha** [comment]
There seems to be issue with following command

ballerina --all test  --b7a.config.file=/tests/ballerina.conf

**Comment by warunalakshitha** [comment]
ballerina  test --all -- --b7a.config.file=/tests/ballerina.conf works So I hope we are good.

**Comment by pubudu91** [comment]
These are ok. Found an issue in doc command. Will open an issue for it

**Pull request merged**
