### PR TITLE
Update netty version [1.2.x]

### PR DESCRIPTION
**Pull request by keizer619**

### CODE REVIEW

**Comment by ldclakmal** [comment]
@chamil321 I think we need to bump the `netty` versions of the `wso2-transport` and `tcnative` versions of both `ballerina-lang` and `wso2-transport`. Could you please check on this?

**Comment by ldclakmal** [comment]
testerina test cases are failing in windows job here. @azinneera Could you please check into these?

**Comment by ldclakmal** [comment]
gRPC test cases are failing in this PR now. @MadhukaHarith92 @dilanSachi Could you please check into these?

**Comment by ldclakmal** [comment]
HTTP2 and Transaction tests are failing. @chamil321 and @chiranSachintha Could you please check into these?

**Comment by pcnfernando** [comment]
@lasinicl can you check on the trx failure

**Comment by lasinicl** [comment]
> @lasinicl can you check on the trx failure

The transaction test passed locally for me, and the transaction module doesn't have any netty dependencies. Not sure why the test failed. :thinking:

**Comment by pcnfernando** [comment]
Retriggering seems to have passed the transaction tests

**Comment by Bhashinee** [comment]
> HTTP2 and Transaction tests are failing. @chamil321 and @pcnfernando Could you please check into these?

Fixed the HTTP2 failure.

**Pull request merged**
