### PR TITLE
Introduce a null check for type prior to element type check

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
$Title.

### CODE REVIEW

**Comment by Kishanthan** [comment]
@MaryamZi , test case ?

**Comment by MaryamZi** [comment]
@Kishanthan this is to fix an NPE thrown at the [getElementType(BType type)](https://github.com/ballerina-platform/ballerina-lang/pull/9822/files#diff-1bd18f7cff16bc33f5eed928c59f69b9R152) method, if the [constructor](https://github.com/ballerina-platform/ballerina-lang/pull/9822/files#diff-1bd18f7cff16bc33f5eed928c59f69b9R68) accepting no args is used and thus array type is not set.

Do we need a test case for this particular scenario?

**Comment by MaryamZi** [comment]
@hasithaa agreed, will work on fixing usages of this constructor. Will also work on fixing instances where the type is set incorrectly (element type instead of array type encapsulating element type), as discussed.

**Comment by MaryamZi** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/10057 to track fixing incorrect/inconsistent usage, as discussed offline.

Closing this PR since this change would not be needed once the above issue is fixed.

**Pull request closed without merging**
