### PR TITLE
Fix remove re-declared import code action is not suggested for modules in the current package

### LINKED ISSUE #38489: [Bug]: `Remove re-declared import` code action is not suggested for modules in the current package
### Description

Consider the following scenario where we try to import the same module twice.

https://user-images.githubusercontent.com/61020198/199156769-5a0e886b-b70b-40ac-8bdb-b7742f7ba3f9.mov

The diagnostic we get here is `redeclared symbol 'module1' (BCE2008)` not `redeclared import module (BCE2004)`

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Editor

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by DamithaSenevirathne**
Fixes #38489 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by gayalkuruppu — APPROVED** [review]
Changes look good. Shall we create another issue to track `Remove all unused imports` not working?

**Review by malinthar — DISMISSED** [review]
LGTM!

**Review by IMS94 — APPROVED** [review]

**Comment by IMS94** [comment]
> Changes look good. Shall we create another issue to track the problem with `Remove all unused imports`? If the code action doesn't change anything, we should not show the code action in the first place IMO.

@DamithaSenevirathne can you check this and create an issue accordingly?

**Comment by DamithaSenevirathne** [comment]
> > Changes look good. Shall we create another issue to track the problem with `Remove all unused imports`? If the code action doesn't change anything, we should not show the code action in the first place IMO.
> 
> @DamithaSenevirathne can you check this and create an issue accordingly?

@IMS94 https://github.com/ballerina-platform/ballerina-lang/issues/38784

**Review by hasithaa — APPROVED** [review]
LGTM, Please get reviewed from LangServer team.

**Review by IMS94 — APPROVED** [review]

**Pull request merged**
