### PR TITLE
Fix pruning issue in `block-stmt` parsing

### LINKED ISSUE #34568: Token missing in the parsed ST for the invalid code
**Description:**
Consider the following invalid code.
```bal
public function main() {
    {
        io:println("a");
        io:println("b");
    }
}
```
It is parsed as,
```bal
public function main() {
    {
println("a");
        io:println("b");
    }
}
```
Notice that the first `io` is missing in the generated ST.

### PR DESCRIPTION
**Pull request by lochana-chathura**
## Purpose
$subject.

Fixes #34568 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by KRVPerera — COMMENTED** [review]
I agree with the parser change. But if the original ballerina code is invalid we should also provide information for the user to actually fix the issue. I think this is not properly defined in spec but looks like the parser may define the inner block as a statement. Then there is also another approach to fixing the semantic analyzer to properly resolve the environment to find `io:println` properly. WDYT?

**Review by KRVPerera — APPROVED** [review]

**Comment by rdulmina** [comment]
> I agree with the parser change. But if the original ballerina code is invalid we should also provide information for the user to actually fix the issue. I think this is not properly defined in spec but looks like the parser may define the inner block as a statement. Then there is also another approach to fixing the semantic analyzer to properly resolve the environment to find `io:println` properly. WDYT?

Can u explain with a sample code?

**Comment by lochana-chathura** [comment]
Looks like `block-stmt` was just another statement in our old spec (2020 june - by the time we wrote the new parser) https://ballerina.io/spec/lang/draft/v2020-06-18/#statement and later it has been removed from the spec. According to the current spec, it is invalid and we seem to still support it in our implementation.

**Comment by lochana-chathura** [comment]
>Then there is also another approach to fixing the semantic analyzer to properly resolve the environment to find `io:println` properly. WDYT?

The parsing issue fixed here was only caused when the first statement in the `block-stmt` is `io:println()`.
i.e. The following sample works in GA,
```bal
public function main() {
    {
        int x = 3;
        x += 2;
        io:println(x);
    }
}
```

**Comment by lochana-chathura** [comment]
> Looks like `block-stmt` was just another statement in our old spec (2020 june - by the time we wrote the new parser) https://ballerina.io/spec/lang/draft/v2020-06-18/#statement and later it has been removed from the spec. According to the current spec, it is invalid and we seem to still support it in our implementation.

Currently `block-stmt` is equivalent to the `do-stmt` with `no on-fail-caluse`. That could be the reason for the spec not having a `block-stmt`. Will create an issue for this. We can give `missing 'do' keyword` diagnostic.

**Review by pcnfernando — APPROVED** [review]

**Comment by pcnfernando** [comment]
> #34568

Point the issue as a reply

> > Looks like `block-stmt` was just another statement in our old spec (2020 june - by the time we wrote the new parser) https://ballerina.io/spec/lang/draft/v2020-06-18/#statement and later it has been removed from the spec. According to the current spec, it is invalid and we seem to still support it in our implementation.
> 
> Currently `block-stmt` is equivalent to the `do-stmt` with no `on-fail-caluse`. That could be the reason for the spec not having a `block-stmt`. Will create an issue for this. We can give `missing 'do' keyword` diagnostic.

Please point the issue as a reply

**Comment by lochana-chathura** [comment]
> Please point the issue as a reply @lochana-chathura

Created #36187

**Pull request merged**
