### PR TITLE
[Improve] Snippet Improve for `service/http`

### PR DESCRIPTION
**Pull request by athiththan11**
## Purpose

This PR contains an improvement for the `service/http` snippet generation. As default, the created snippet has placeholders for `serviceName`, `newResource` and etc. and the listener ports are ignored. Hence, improved the snippet template to support the `Listener Port` stop, and also to tab stop at the Resource Function's body.

### CODE REVIEW

**Review by nadeeshaan — CHANGES_REQUESTED** [review]
We need to enable the snippet suggestion as well. We have already disabled these snippets in `SnippetGenerator` and also in `ModulepartNodeContext`. Shall we fix those as well?

**Comment by athiththan11** [comment]
Hi @nadeeshaan 

Can you provide me some guidance on what and where to fix the Snippet Generator suggestions? (as I am still learning the repo and the structure to contribute more :))

**Comment by rasika** [comment]
@athiththan11 there are some conflicting changes, can you please sync your PR with latest master branch. We have already enabled this snippet now.

**Comment by athiththan11** [comment]
Hi @rasika / @nadeeshaan 
I have made the required changes and merged the conflicts. It seems now the Integration tests are failing due to the changes introduced in commit [https://github.com/ballerina-platform/ballerina-lang/commit/cb1ac85f13d707910ed67f582f0d010f74133b12](https://github.com/ballerina-platform/ballerina-lang/commit/cb1ac85f13d707910ed67f582f0d010f74133b12).

Appreciate it if these also need to be updated with the new patterns.

**Comment by nadeeshaan** [comment]
Since there are conflicts and also, the particular snippet have been improved, closing the PR.

**Pull request closed without merging**
