### PR TITLE
Add the semantic model to the compilation

### PR DESCRIPTION
**Pull request by pramodya1994**
## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by Kishanthan — COMMENTED** [review]
What about PackageCompilation? Don't we need a way to get semantic model of modules within package compilation as well?

@sameerajayasoma @pramodya1994

**Comment by sameerajayasoma** [comment]
I think we need that to support the doc requirements. @hevayo ?

**Comment by sameerajayasoma** [comment]
This PR contains many classes. Do we know why?

**Comment by pramodya1994** [comment]
> This PR contains many classes. Do we know why?

I synced with the master to get changes done to move the compiler API to the ballerina-lang module

**Review by Kishanthan — COMMENTED** [review]
LGTM

**Review by Kishanthan — APPROVED** [review]

**Review by Kishanthan — APPROVED** [review]

**Pull request merged**
