### PR TITLE
Add verbose for push and pull commands

### PR DESCRIPTION
**Pull request by pramodya1994**
- Fixes https://github.com/ballerina-platform/ballerina-lang/issues/8885

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by hasithaa** [comment]
How we can test this kind of functionality?

**Comment by pramodya1994** [comment]
> How we can test this kind of functionality?

We are going to add tests for this in ballerina-distribution.

**Review by azinneera — COMMENTED** [review]
Do we have distribution tests for this?

**Comment by anupama-pathirage** [comment]
@azinneera I have removed the `stale` lable assuming this work is not needed anymore. Then it won't get added to the `[Stale PR] Ballerina Stale PR Details` mail in the future.

**Pull request closed without merging**
