### PR TITLE
Fix issues in endBB assignments for local variables

### LINKED ISSUE #35591: Codecov report generation fails due to localVar endBB changes
**Description:**
This issue is observed when using graphql, with the fix introduced in the PR https://github.com/ballerina-platform/ballerina-lang/pull/34131

**Steps to reproduce:**

**Affected Versions:**
2201.0.1, 2201.0.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gabilang**
Fixes #35591

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Shall we test with graph-ql repo as well?

**Comment by gabilang** [comment]
> Shall we test with graph-ql repo as well?

Tested with `graph-ql` module. Build was successful.

**Comment by gabilang** [comment]
A [duplicate](https://github.com/ballerina-platform/ballerina-lang/pull/35688) of this PR has been sent to the staging branch `2201.0.3-stage-new`

**Comment by warunalakshitha** [comment]
I have merged https://github.com/ballerina-platform/ballerina-lang/pull/35688 hence closing this.

**Pull request closed without merging**
