### PR TITLE
 Add Match Expression completion support

### LINKED ISSUE #8418: "but" Keyword based suggestions needs to be implemented
**Description:**
In the current Language Server completion implementation, "but" keyword related suggestions are not supported

**Affected Versions:**
v0.970.0

### PR DESCRIPTION
**Pull request by nadeeshaan**
Resolves #8418 

ezgif com-video-to-gif

### CODE REVIEW

**Comment by TylerJewell** [comment]
I noticed that in the recommendation, it is giving you an absolute list of the types in the match completion. What if a user wants to only match one type and then catch the rest with an any? Is there any way to offer both types of completion?

**Comment by nadeeshaan** [comment]
@TylerJewell, What if we follow the same flow we used for annotation attachments? You get individual options, all option filler as well as in this case any type?

**Comment by TylerJewell** [comment]
Yeah, I think that would be consistent and a good option.

**Comment by nadeeshaan** [comment]
@TylerJewell updated the PR with the suggestions and you can see the working demo in the description

**Pull request merged**
