### PR TITLE
Improve `isRemoteManagementEnabled` runtime API name

### PR DESCRIPTION
**Pull request by HindujaB**
## Purpose
$subject
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/43267

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by ravinperera00 — APPROVED** [review]
LGTM

**Comment by warunalakshitha** [comment]
+1 to go with isRemoteManagementEnabled

**Comment by warunalakshitha** [comment]
Lets create an issue for this.

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Pull request merged**
