### PR TITLE
Make redundant info logs in transaction module debug logs

### LINKED ISSUE #26367: Remove redundant test logs in ballerina transaction manager.
**Description:**
$subject for the following logs.

Checked with @afkham who was the author of the code and those are INFO logs added to validate the behaviour. We can safely remvoe them as it is not meaningful for the end user. 

```
2020-03-18 12:36:26,983 INFO  [ballerina/transactions] - Created transaction: 17130bbc-28e0-414d-b0a0-e20efccdacec
Inserted count: 1
2020-03-18 12:36:26,999 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: 17130bbc-28e0-414d-b0a0-e20efccdacec:$anon$.$0
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by gimantha**
Fixes #26367

### CODE REVIEW

**Comment by mohanvive** [comment]
@gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )

**Comment by gimantha** [comment]
> @gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )

@mohanvive In Ballerina we don't have such method. For Java files I have checked that case.

**Comment by mohanvive** [comment]
> > @gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )
> 
> @mohanvive In Ballerina we don't have such method. For Java files I have checked that case.

OK, got it.

**Review by mohanvive — APPROVED** [review]

**Review by anupama-pathirage — APPROVED** [review]

**Comment by MaryamZi** [comment]
> > @gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )
> 
> @mohanvive In Ballerina we don't have such method. For Java files I have checked that case.

We can use the function pointer approach in such scenarios, right? https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/examples/log-api/log_api.bal#L41

**Comment by anupama-pathirage** [comment]
> > > @gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )
> > 
> > 
> > @mohanvive In Ballerina we don't have such method. For Java files I have checked that case.
> 
> We can use the function pointer approach in such scenarios, right? https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/examples/log-api/log_api.bal#L41

Yes.  @gimantha Shall we do this improvement? Lets go with the current code in 1.2.9 as release is trigeering soon. But can u send the fix to 1.2.x branch and master branch?

**Comment by gimantha** [comment]
> > > > @gimantha Any reason to avoid `isDebugEnabled` check in other places (Since there are string concatenation, it would be good to add isDebugEnabled check in critical flows )
> > > 
> > > 
> > > @mohanvive In Ballerina we don't have such method. For Java files I have checked that case.
> > 
> > 
> > We can use the function pointer approach in such scenarios, right? https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/examples/log-api/log_api.bal#L41
> 
> Yes. @gimantha Shall we do this improvement? Lets go with the current code in 1.2.9 as release is trigeering soon. But can u send the fix to 1.2.x branch and master branch?

@anupama-pathirage @MaryamZi I will send another PR to 1.2.x branch with this change.

**Pull request merged**
