### PR TITLE
feat: getAllDependents & getAllDependencies

### LINKED ISSUE #36113: Add `getAllDependents` and `getAllDependencies` method to the DependencyGraph class
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyGraph.java

```java
    // Returns all direct and indirect dependents of the node T
    public Collection<T> getAllDependents(T node) {
    }

    // Returns all direct and indirect dependencies of node T 
    public Collection<T> getAllDependencies(T node) {
    }
```

### PR DESCRIPTION
**Pull request by adripo**
Fixes #36113

## Approach
In the modified code, I've added two new methods: getAllDependents and getAllDependencies. These methods use recursion to traverse the graph and collect all direct and indirect dependents/dependencies of a given node. The helper methods getAllDependentsRecursive and getAllDependenciesRecursive are used for the recursive traversal.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by sameerajayasoma — CHANGES_REQUESTED** [review]
This code looks perfect. 

Can you please add some unit test cases to validate your implementation to this test class? 
https://github.com/ballerina-platform/ballerina-lang/blob/727eb0fa32ec496c82b88deb9a019347eeb856ff/project-api/project-api-test/src/test/java/io/ballerina/projects/test/DependencyGraphTests.java#L632

Since the `DependencyGraph<T>` accepts any T, you can use a custom object as the node.

**Comment by adripo** [comment]
I created the tests as requested

**Comment by adripo** [comment]
@sameerajayasoma could you also label the PR as hacktoberfest-accepted before 31 october? Thank you

**Review by sameerajayasoma — DISMISSED** [review]
Changes look great!!! Thanks for your contribution.

**Review by sameerajayasoma — APPROVED** [review]

**Review by sameerajayasoma — APPROVED** [review]

**Pull request merged**
