### PR TITLE
Fix df analysis failure for object init method as outside method def and disallow extern object init methods

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose
This PR
- fixes the failure at data flow analysis phase when an object init method is defined as an outside method
- disallows extern object init methods

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/12812

### CODE REVIEW

**Comment by lankavitharana** [comment]
any reason for not allowing extern?

**Comment by MaryamZi** [comment]
@lankavitharana 
> any reason for not allowing extern?

This is because dataflow analysis cannot be done with extern __init() functions.

**Comment by lankavitharana** [comment]
it's kind of like a technicality right? my point is can we say we are not allowing it because we can't do data flow analysis? if we take data flow analysis, we need that to identify whether all the fields are initialized right? so there can be scenarios where we have default values for all the fields, in which case we don't need to analyze init function. Of course, if we don't have default values, then we have to have an analyzable init function.

**Comment by MaryamZi** [comment]
Yeah agreed. It would be the same even on the off chance there is an object with all private/no fields. But do we need to allow this, given that we are not expecting many extern functions anyway? 

Also, IMO, whatever logic in the init function (including setting values for object fields) should ideally be written in Ballerina. If by any chance someone actually wants to perform some extern logic it could be a separate extern function invocation within the init function. WDYT?

**Comment by lankavitharana** [comment]
I think that's a better answer than the previous one :) 
+1

**Pull request merged**
