### PR TITLE
Fix `Replace with` CA comment suggesting

### LINKED ISSUE #34908: `Replace with` code action duplicates commented out codes
**Description:**

When applied the code action `Replace with ...` right after `io:` the comments right before it gets doubled. The code action is misleading to the user IMO.

https://user-images.githubusercontent.com/46120162/151824346-7bef878f-4ad9-4ee7-9281-a6c721d9d7a2.mp4

**Steps to reproduce:**

type `io:` at the cursor and apply the code action `Replace with...`
```
import ballerina/io;

public function main() {
    // fake 
    // lines
    // of
    // comments
    <cur>
}
```

**Affected Versions:**
SL 2201.0.0

**Related Issues**
#34581 
#34714

### PR DESCRIPTION
**Pull request by LakshanWeerasinghe**
## Purpose
$subject

Fixes #34908

## Approach
In the `QualifiedIdentifierCodeAction` class when getting the code action info, the qualified name (syntax) should be selected. In the previous implementation the comments also getting selected due to usage of `           node.modulePrefix().toSourceCode().strip()`. Change it to `node.modulePrefix().text()` so only the syntax getting selected.

## Check List 
- [x ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ x] Added necessary tests
  - [x ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by dulajdilshan** [comment]
It would be better if you do the changes on a separate branch instead of your forked `master`. It will be a good practice. For now this is fine

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Comment by mohanvive** [comment]
@LakshanWeerasinghe In future please follow the guidelines given in [1] when providing git commit messages.

[1] https://cbea.ms/git-commit/

**Comment by LakshanWeerasinghe** [comment]
@mohanvive I will update it accordingly.

**Comment by LakshanWeerasinghe** [comment]
> It would be better if you do the changes on a separate branch instead of your forked `master`. It will be a good practice. For now this is fine

Created a new PR with the new branch

**Pull request closed without merging**
