### PR TITLE
Add Azure pipeline config

### PR DESCRIPTION
**Pull request by Shan1024**
## Purpose
This PR adds [Azure pipeline](https://dev.azure.com) config to the repo. By adding Azure pipeline support in the Ballerina repo, we can build each PR in Windows, Ubuntu and MacOS. So any build failure particular to these OSs can be identified beforehand.

### CODE REVIEW

**Comment by riyafa** [comment]
A small issue here. Seems azure builds each commit pushed after a PR is sent. This means it will take a long time if people keep pushing to an open PR. Is it not possible to make sure that it builds only the latest commit in a PR?

**Comment by Shan1024** [comment]
@riyafa - That depends on how do you define the latest commit. When I push some commits, it will build the last commit. But later when I add few other commits and push them, it will again build the last commit of the newly added commit. This is how usually it happens in the Travis and AppVeyor as well. 

In Travis, we can configure to stop a pending build if a new commit is pushed. But if a build has already started, it will continue unless we stop it manually.

So what we can do is, not pushing commits one by one. Maybe we can push the commits when we are confident that the changes are done.

**Comment by riyafa** [comment]
Thanks for the explanation. What I wanted to check was if we could cancel the pending builds in azure if a new commit is pushed?

**Comment by Shan1024** [comment]
AFAIK, we have to manually stop the build. But I'll check whether there is any configuration to do this automatically.

**Pull request merged**
