### PR TITLE
[Refactoring] Names and Name cleanup (use static access & getter)

### PR DESCRIPTION
**Pull request by Shadow-Devil**
## Purpose
- Made all methods of the [Names](https://github.com/ballerina-platform/ballerina-lang/blob/904650aa7635fdfbeb8280150ca9f44a0bbddbff/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java) class static, since they access no instance fields.
- Remove all references to local `Names` variables and only use static access
- Encapsulate [Name.value](https://github.com/ballerina-platform/ballerina-lang/blob/281e0d8f9602b8ed939be92797484970624ab553/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Name.java#L25) field (make it private and only use `getValue()`).

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by heshanpadmasiri** [comment]
@Shadow-Devil first of all thank you very much for taking time to do this refactoring and I generally agree with almost all the changes, with one minor caveat. You may have seen in many places we have direct access to fields instead of going via encapsulated methods. Rational for this is as fallows

1. If we do a direct field access we get a `getField` instruction instead of `invokeVirtual` instruction which is faster from the get go
2. C2 can optimise `invokeVirtual`  in the hot sections to be just as fast as `getField` assuming class is final (otherwise it has to do a class word check even if we don't actually extend the class since we could be loading classes dynamically from the JVMs perspective)
3. But in most cases (with exception being the parts used by language server) our compiler don't run long enough to be fully "jitted" (so back to 1)

Given with your changes `Name.value` is anyway final (and its a string which is immutable) I think the only benefit we can get by using the encapsulated method is,
1. We can add some validation or other logic to the accessor in the future
2. We can use the interface (note `invokeInterface` as far as I know don't get same treatment as `invokeVirutal` when there is a single class implementing it, so it would always has the class word check even after "jitting")

Therefore I think it is better to cross that bridge when we need to do 1 since I don't see in many places we need to do 2. WDYT?

**Comment by Shadow-Devil** [comment]
@heshanpadmasiri oh wow, thank you for that deep analysis! Do you know what would happen, if we made Name a record? then one would have to use the accessors and (i hope) the invokeVirtial could be optimised away. Downside is, that the methodname would change from getValue() to value() and many libraries which use this field would need to be updated as well. WDYT?

**Comment by Shadow-Devil** [comment]
As I understand the Name class is pretty much only a wrapper of a String.
This would be nicely modeled by Kotlins [inline value classes](https://kotlinlang.org/docs/inline-classes.html) which will optimize the wrapper class while compiling but still offering typesafety.
In Java there is also work in this direction with [JEP 401](https://openjdk.org/jeps/401) but this is currently still a draft.

**Comment by Shadow-Devil** [comment]
@heshanpadmasiri If you think we should not do this change, close the PR please so I know that this will not be included. I do understand your points but still think these micro optimisations might not be enough to go against the Java Standard of having getters instead of directly accessing the property. Maybe also others could share their opinion on this topic :)

**Pull request closed without merging**
