### PR TITLE
Fix sorting in mapping constructor context

### LINKED ISSUE #33623: Auto-completions spec conformance for the `MappingConstructorExpression`
**Description:**
$title
https://ballerina.io/spec/lang/master/#mapping-constructor-expr

### PR DESCRIPTION
**Pull request by nadeeshaan**
## Purpose
Fixes #33623 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by IMS94 — APPROVED** [review]
LGTM!

**Review by gayalkuruppu — COMMENTED** [review]
```
type Pet record {|
    string name;
    int 'type;
|};

type Dot record {|
    string name;
    int 'type;
|};

public function main() {
    Pet[] pets = [];
    Dot[] dots = [];

    pets.push({});
    dots.push({});

    PetStore petStore = new;
    petStore.addPets({<cur>});
    petStore.addPet({});
}

class PetStore {

    function addPets(Pet[] pets) {
        
    }

    function addPet(Pet pet) {
        
    }
}
```
Is there a way that we can give priority for the suggestion `pets` over `dots` at the cursor in this scenario?

**Comment by nadeeshaan** [comment]
> ```
> type Pet record {|
>     string name;
>     int 'type;
> |};
> 
> type Dot record {|
>     string name;
>     int 'type;
> |};
> 
> public function main() {
>     Pet[] pets = [];
>     Dot[] dots = [];
> 
>     pets.push({});
>     dots.push({});
> 
>     PetStore petStore = new;
>     petStore.addPets({<cur>});
>     petStore.addPet({});
> }
> 
> class PetStore {
> 
>     function addPets(Pet[] pets) {
>         
>     }
> 
>     function addPet(Pet pet) {
>         
>     }
> }
> ```
> 
> Is there a way that we can give priority for the suggestion `pets` over `dots` at the cursor in this scenario?

As I understood, at the given cursor position we just suggest the available variables for the mapping constructor. We cannot make a decision to sort the content since what we are trying to add as a parameter is semantically ambiguous in this context. But I think you have a good point here, and we can address this with some other UX, such as with an associated refactoring option - additional text edits. WDYT?

**Comment by gayalkuruppu** [comment]
> > ```
> > type Pet record {|
> >     string name;
> >     int 'type;
> > |};
> > 
> > type Dot record {|
> >     string name;
> >     int 'type;
> > |};
> > 
> > public function main() {
> >     Pet[] pets = [];
> >     Dot[] dots = [];
> > 
> >     pets.push({});
> >     dots.push({});
> > 
> >     PetStore petStore = new;
> >     petStore.addPets({<cur>});
> >     petStore.addPet({});
> > }
> > 
> > class PetStore {
> > 
> >     function addPets(Pet[] pets) {
> >         
> >     }
> > 
> >     function addPet(Pet pet) {
> >         
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a way that we can give priority for the suggestion `pets` over `dots` at the cursor in this scenario?
> 
> As I understood, at the given cursor position we just suggest the available variables for the mapping constructor. We cannot make a decision to sort the content since what we are trying to add as a parameter is semantically ambiguous in this context. But I think you have a good point here, and we can address this with some other UX, such as with an associated refactoring option - additional text edits. WDYT?

+1

**Pull request merged**
