### PR TITLE
Enable retrieving diagnostic meta-data for assignment-required diagnostic messages

### LINKED ISSUE #28123: Retrieving diagnostic meta-data for Assignment-Required diagnostic message
**Description:**
In language server, there's a requirement to retrieve the provided BType of the expression inorder to provide quickfix code-actions.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by dulajdilshan**
## Purpose
$title

Fixes #28123 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by anupama-pathirage** [comment]
@dulajdilshan The commit messages and PR heading is not according to the best practices. Please correct them.

A properly formed Git commit subject line should always be able to complete the following sentence:

If applied, this commit will **_your subject line here_**

Refer [1] for more details.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

**Comment by dulajdilshan** [comment]
> @dulajdilshan The commit messages and PR heading is not according to the best practices. Please correct them.
> 
> A properly formed Git commit subject line should always be able to complete the following sentence:
> 
> If applied, this commit will **_your subject line here_**
> 
> Refer [1] for more details.
> 
> [1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md#submit-your-contribution

I'll change. Thanks

**Review by rasika — APPROVED** [review]
LGTM

**Review by IMS94 — APPROVED** [review]
LGTM! Except for the fact that commit message 1st line should not exceed 50 characters as per the convention we follow.

**Pull request merged**
