### PR TITLE
Add `.signature()` method validation test cases of XML sub-types in Semantic API

### LINKED ISSUE #35882: Check and add test cases for `.signature()` method of XML sub type symbols in Semantic API
**Description:**
Consider the following code Segment.

```
type XmlEle xml:Element;
type XmlPI xml:ProcessingInstruction;
type XmlCmnt xml:Comment;
type XmlTxt xml:Text;

public function main() {
    xml<XXMLele> a = xml ``;
}
```

**Describe your task(s)**
Write test cases to validate the `.signature()` method of the type descriptors obtained using the above-like type definitions referring to XML subtypes.

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #35882

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by dulajdilshan** [comment]
Do we need to merge [37080](https://github.com/ballerina-platform/ballerina-lang/pull/37080/commits) before this?

**Comment by mohanvive** [comment]
Please fix the conflicts. @sanjana

**Comment by sanjana** [comment]
> Do we need to merge [37080](https://github.com/ballerina-platform/ballerina-lang/pull/37080/commits) before this? (This Pr has commits related to #37080)

@dulajdilshan it was done in order to minimize the conflict resolving process since both the PRs had changes to be done in the same set of files.

**Comment by sanjana** [comment]
> Please fix the conflicts. @sanjana

@mohanvive, sure. Updated the PR. Let's wait for the checks to pass.

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Pull request merged**
