### PR TITLE
Implement equals and hashCode functions in NodeLocation

### LINKED ISSUE #32290: `ModuleLoadRequest.locations` list grows abnormally leading to OOM
**Description:**
While debugging for #32020, we encountered an OOM scenario. While the main cause for the OOM is #32289, we noticed an abnormal growth in `ModuleLoadRequest.locations` list. Corresponding heap dump is attached here.

After reproducing the OOM scenario, we noticed aroud 800 objects in the above list.

**Heap Dump**
https://drive.google.com/file/d/1DTho2ewn8UJhyGjG99wJxjzOjmQM8xzK/view?usp=sharing

ModuleLoadRequest1

**Steps to reproduce:**
We produced this in `nballerina` project with the steps mentioned in [this comment](https://github.com/ballerina-platform/ballerina-lang/issues/32020#issuecomment-903504701).

**Affected Versions:**
SL Beta 3 Snapshot

### PR DESCRIPTION
**Pull request by IMS94**
## Purpose
$subject
This is to avoid a memory leak inside `ModuleLoadRequest`s where it's keeping track of locations as `NodeLocation`s inside a set.

Fixes #32290 

## Approach
Implemented `equals()` and `hashCode()` methods in `NodeLocation` class

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by mohanvive — APPROVED** [review]
LGTM.

**Comment by mohanvive** [comment]
@hevayo @azinneera Appreciate it if you review and merge this.

**Review by hevayo — COMMENTED** [review]
Do we have any tests for this ?

**Comment by IMS94** [comment]
@hevayo What kind of tests can we add here? Unit tests for the `equals()` and `hashCode()` methods?

**Comment by hevayo** [comment]
Yeh unit tests will do

**Comment by IMS94** [comment]
@hevayo Can you have a look now?

**Review by sameerajayasoma — APPROVED** [review]
LGTM.

But this is not the proper fix for the location growth problem. We will come up with a proper fix soon. I captured the requirement in this issue:

https://github.com/ballerina-platform/ballerina-lang/issues/32497

**Review by hevayo — APPROVED** [review]

**Pull request merged**
