### PR TITLE
Fix trigger service test

### PR DESCRIPTION
**Pull request by HasithaAthukorala**
Fixes #<Issue Number>

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by azinneera — APPROVED** [review]
Calls to central should be avoided in ballerina-lang repo. We can merge this to get the build working. Ideal fix is to mock the central calls. If the central calls are needed, then we should move it to the ballerina-distribution repo. Please create an issue to track this.

**Comment by HasithaAthukorala** [comment]
Sure, I'll create the issue and mention here

**Comment by MaryamZi** [comment]
@HasithaAthukorala, shall we send a PR with this change to the master branch also? Since we may not sync this branch immediately.

**Comment by HasithaAthukorala** [comment]
@MaryamZi Sent the PR to the master as well, https://github.com/ballerina-platform/ballerina-lang/pull/34232

**Comment by HasithaAthukorala** [comment]
Created the issue https://github.com/ballerina-platform/ballerina-lang/issues/34234

**Pull request merged**
