### PR TITLE
Add test case to clarify method overloading in java interop functions

### LINKED ISSUE #20918: Interop functions do not identify specific overloaded methods
**Description:**
When there is a call for an overloaded method, Java finds the most specific overloaded method to execute. But Ballerina java interop functions does not identify this. Instead, it throws an error at the build, stating 
```
{ballerinax/java}OVERLOADED_METHODS message=More than one public methods <method_name> that match with the parameter types '<paramter_types>' found in class '<class_path>'.
```
But ideally, if there are more than one matching function, it should select the most specific method to execute.
```

**Steps to reproduce:**

create two ballerina interop functions:

```ballerina
function foo(handle str) returns any {
    name: "foo",
    class: "org.sample.interop.MyClass",
    paramTypes: ["java.lang.String"]
} external;

function bar(any val) returns any {
    name: "foo",
    class: "org.sample.interop.MyClass",
    paramTypes: ["java.lang.Object"]
} external;
```

Define the java class accordingly, and try to build this. It will throw the above mentioned error.

**Affected Versions:**
Master branch.

### PR DESCRIPTION
**Pull request by HindujaB**
Fixes #20918 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by HindujaB** [comment]
> Can we address the changes we requested during the sprint meeting on this PR?

the changes are addressed in the latest commit.

**Comment by Kishanthan** [comment]
One of your commit (https://github.com/ballerina-platform/ballerina-lang/pull/22999/commits/066ce0fb003e8bce7876d9c49079de6d37591580) message exceeds the allowed char limit. Please fix it.

**Comment by HindujaB** [comment]
> One of your commit ([066ce0f](https://github.com/ballerina-platform/ballerina-lang/commit/066ce0fb003e8bce7876d9c49079de6d37591580)) message exceeds the allowed char limit. Please fix it.
Updated the commit message

**Comment by ThisaruGuruge** [comment]
This added test does not cover the scenario mentioned in the #20918.

One of the overloaded type should be a child of the other. Like the example given in the mentioned issue, one is an `Object` and the other is a  `String`, which is a child of the `Object`.

**Pull request merged**
