### PR TITLE
Remove `ballerina/oauth2` module

### PR DESCRIPTION
**Pull request by ldclakmal**
## Purpose
This PR removes `ballerina/oauth2` module from `master` branch since it is migrated to https://github.com/ballerina-platform/module-ballerina-oauth2

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by aashikam** [comment]
This has a lot of usages in language-server related json files also. 
Screen Shot 2020-08-27 at 8 09 53 AM

**Comment by ldclakmal** [comment]
@aashikam Yes true. There are more than 150+ usages in language server files. We can fix those json files before we merge the `stdlib-remove` branch to `master`. Otherwise, there may be lot of conflicts if everyone tried to fix language server files. WDYT?

**Comment by aashikam** [comment]
> @aashikam Yes true. There are more than 150+ usages in language server files. We can fix those json files before we merge the `stdlib-remove` branch to `master`. Otherwise, there may be lot of conflicts if everyone tried to fix language server files. WDYT?

Yeah it's better if we can skip that in all of the PRs then. WDYT @BuddhiWathsala

**Review by aashikam — COMMENTED** [review]
LGTM

**Comment by BuddhiWathsala** [comment]
> > @aashikam Yes true. There are more than 150+ usages in language server files. We can fix those json files before we merge the `stdlib-remove` branch to `master`. Otherwise, there may be lot of conflicts if everyone tried to fix language server files. WDYT?
> 
> Yeah it's better if we can skip that in all of the PRs then. WDYT @BuddhiWathsala
> One person can send a PR fixing all language-server tests.

+1, during previous PRs also we removed 100+ cases
https://github.com/ballerina-platform/ballerina-lang/pull/22782

**Review by BuddhiWathsala — APPROVED** [review]

**Pull request merged**
