### PR TITLE
Reduce Observability Instrumentation Instructions

### PR DESCRIPTION
**Pull request by nadundesilva**
Related to https://github.com/ballerina-platform/ballerina-lang/issues/29137

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by warunalakshitha** [comment]
Shall we send this to 2.0.0-beta3-dev branch.

**Comment by nadundesilva** [comment]
I am looking into another change that may potentially reduce instructions count (moving to a single error entry without having multiple error entries). But that would take a bit of time.

I can send it in a separate PR and move this to 2.0.0 branch.

**Review by warunalakshitha — APPROVED** [review]
LGTM

**Review by NipunaRanasinghe — APPROVED** [review]
Debugger test framework related changes LGTM

**Pull request merged**
