### PR TITLE
Fix ubuntu build failure

### PR DESCRIPTION
**Pull request by NipunaRanasinghe**
## Purpose
This PR fixes the intermittent CI build failures on ubuntu, which is caused by the code coverage report generation related recent changes.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Review by ThisaruGuruge — APPROVED** [review]

**Comment by sameerajayasoma** [comment]
Do we know why we need to increase the timeout?

**Comment by NipunaRanasinghe** [comment]
> Do we know why we need to increase the timeout?

@sameerajayasoma Yes we do :slightly_smiling_face: While troubleshooting the issue, I found out that its happening due to https://github.com/ballerina-platform/ballerina-lang/pull/29001, where we have merged all 3 previous ubuntu jobs into a single job and it has increased the job build time to ~75 mins (which is same as our build timeout threshold).

**Comment by ThisaruGuruge** [comment]
> Do we know why we need to increase the timeout?

Previously, we had separate phases of the builds running parallel, so the build time for a given build is lesser.
But recently, as a part of the Code Coverage generation, we had to merge all these phases to a single one (Otherwise generating a CodeCov report was impossible). Therefore the build time has increased.

**Comment by manuranga** [comment]
@sameerajayasoma 
I believe it actually it should takes *less* time after combining the steps, but maybe GitHub tracks time per step not per pr as a whole. @keizer619 what do you think?

**Pull request merged**
