### PR TITLE
Update integration tests that integrate with Ballerina Central

### PR DESCRIPTION
**Pull request by NatashaWso2**
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/14285

### CODE REVIEW

**Comment by hasithaa** [comment]
Will close and reopen to trigger travis again.

**Comment by hasithaa** [comment]
@NatashaWso2 Seems like a there is a compilation failure. Can you fix that?

**Comment by NatashaWso2** [comment]
@hasithaa will fix it and update the PR

**Comment by hasithaa** [comment]
@NatashaWso2 It seems like there is a compilation failure. Can you check again?

**Comment by NatashaWso2** [comment]
@hasithaa will check it . Sorry I missed this :(

**Pull request merged**
