### PR TITLE
Enable new parser by default

### PR DESCRIPTION
**Pull request by SupunS**
## Purpose

Disabled some lang-lib tests: #24208
due to 
  - different semantic errors
  - usage of type-descs as expressions.
  - diagnostic positions has not set properly at the transformer

Disabled Error Test: #24207
Disabled WebSubStartupFunctionalityTestCase: #24206

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by manuranga** [comment]
Failed at integration, so re-triggered, but now it seems like it just sitting in the queue.

**Comment by manuranga** [comment]
@SupunS 
I was able to re-enable `ErrorTest` with following change.
Is that code there for different test case?
```diff
--- compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java	(date 1592288613000)
+++ compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/BLangNodeTransformer.java	(date 1592290012000)
@@ -3780,10 +3780,10 @@
             return true;
         }
 
-        if (typeNode.kind() == SyntaxKind.ERROR_TYPE_DESC) {
-            Optional<ErrorTypeParamsNode> typeParam = ((ErrorTypeDescriptorNode) typeNode).errorTypeParamsNode();
-            return typeParam.isPresent() && typeParam.get().parameter().kind() == SyntaxKind.ASTERISK_TOKEN;
-        }
+//        if (typeNode.kind() == SyntaxKind.ERROR_TYPE_DESC) {
+//            Optional<ErrorTypeParamsNode> typeParam = ((ErrorTypeDescriptorNode) typeNode).errorTypeParamsNode();
+//            return typeParam.isPresent() && typeParam.get().parameter().kind() == SyntaxKind.ASTERISK_TOKEN;
+//        }
 
         return false;
     }
```

**Comment by SupunS** [comment]
@manuranga That seems to fix the issue. Pushed the changes.

**Comment by shafreenAnfar** [comment]
Closed and re-opened because github workflow has been updated.

**Pull request merged**
