### PR TITLE
Accept Type reference type symbols as row type param in Table type builder

### LINKED ISSUE #37261: Error throwing when building `TableTypeSymbol` using `TypeReferenceTypeSymbol` as its row type
**Description:**
$subject.

**Steps to reproduce:**
```
type Country record {
    string name;
    decimal area;
};

public function main() {
    Country[] res = [];
    Country[] filteredCountries = from Country c in <cursor>
}
```
My requirement was to build a `TableTypeSymbol` with its `RowType` as `Country`. Below is a example java code.
```
        ------
           Optional<Symbol> optionalSymbol = context.currentSemanticModel().get()
                    .symbol(fromClauseNode.typedBindingPattern().bindingPattern());
            if (optionalSymbol.isEmpty()) {
                return Optional.empty();
            }
            Optional<TypeSymbol> typeSymbol = SymbolUtil.getTypeDescriptor(optionalSymbol.get());
            if (typeSymbol.isEmpty() || typeSymbol.get().typeKind() == TypeDescKind.COMPILATION_ERROR) {
                return Optional.empty();
            }
            
            Types types = context.currentSemanticModel().get().types();
            TypeBuilder builder = types.builder();
            TableTypeSymbol tableTypeSymbol = builder.TABLE_TYPE.withRowType(typeSymbol.get()).build();

        ------
```

Stack Trace of the issue:
Screenshot 2022-08-05 at 10 05 17

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #37261

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by dulajdilshan** [comment]
Will re-open to re-trigger the checks

**Review by dulajdilshan — APPROVED** [review]
LGTM

**Comment by dulajdilshan** [comment]
Corrections to my comment above: Spotbug tests are failing

**Comment by mohanvive** [comment]
@sanjana Spotbugs task is still failing. Check again, please

**Comment by sanjana** [comment]
> @sanjana Spotbugs task is still failing. Check again, please

@mohanvive, checked locally and none failed. Will check again with a re-sync.

**Review by malinthar — APPROVED** [review]
LGTM!

**Pull request merged**
