### PR TITLE
Correct node pos of empty XML template expressions

### LINKED ISSUE #39880: [Bug]: Getting incorrect StringTypeSymbol for xml templates
### Description

Consider the below scenario. In here we should get a XMLTypeSymbol.

```
function name() {
    xml ``.<cursor>
}
```

### Steps to Reproduce

_No response_

### Affected Version(s)

_No response_

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

### PR DESCRIPTION
**Pull request by sanjana**
Fixes #39880

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

### CODE REVIEW

**Comment by pcnfernando** [comment]
Build is failing

**Comment by sanjana** [comment]
> Build is failing

Fixed the failing LS test case in https://github.com/ballerina-platform/ballerina-lang/pull/40044/commits/9cf8e144388ba3f0c141bd8fad7ff6782812bc5e.

**Review by LakshanWeerasinghe — APPROVED** [review]
LGTM!

**Review by pcnfernando — APPROVED** [review]

**Comment by pcnfernando** [comment]
@IMS94 can you please have a look

**Review by malinthar — APPROVED** [review]

**Pull request merged**
